<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('field_data_field_vid_emb', array(
  'fields' => array(
    'entity_type' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'bundle' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'deleted' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ),
    'entity_id' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'revision_id' => array(
      'type' => 'int',
      'not null' => FALSE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'language' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '32',
      'default' => '',
    ),
    'delta' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'field_vid_emb_video_url' => array(
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '512',
      'default' => '',
    ),
    'field_vid_emb_thumbnail_path' => array(
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '512',
      'default' => '',
    ),
    'field_vid_emb_video_data' => array(
      'type' => 'blob',
      'not null' => FALSE,
      'size' => 'big',
    ),
    'field_vid_emb_embed_code' => array(
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '1024',
      'default' => '',
    ),
    'field_vid_emb_description' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
  ),
  'primary key' => array(
    'entity_type',
    'entity_id',
    'deleted',
    'delta',
    'language',
  ),
  'indexes' => array(
    'entity_type' => array(
      'entity_type',
    ),
    'bundle' => array(
      'bundle',
    ),
    'deleted' => array(
      'deleted',
    ),
    'entity_id' => array(
      'entity_id',
    ),
    'revision_id' => array(
      'revision_id',
    ),
    'language' => array(
      'language',
    ),
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('field_data_field_vid_emb')
->fields(array(
  'entity_type',
  'bundle',
  'deleted',
  'entity_id',
  'revision_id',
  'language',
  'delta',
  'field_vid_emb_video_url',
  'field_vid_emb_thumbnail_path',
  'field_vid_emb_video_data',
  'field_vid_emb_embed_code',
  'field_vid_emb_description',
))
->values(array(
  'entity_type' => 'node',
  'bundle' => 'vef_content',
  'deleted' => '0',
  'entity_id' => '3273427',
  'revision_id' => '3273427',
  'language' => 'und',
  'delta' => '0',
  'field_vid_emb_video_url' => 'https://www.youtube.com/watch?v=ibqBuhVtACk&ab_channel=LoveBabbar',
  'field_vid_emb_thumbnail_path' => 'public://video_embed_field_thumbnails/youtube/ibqBuhVtACk.jpg',
  'field_vid_emb_video_data' => 'a:1:{s:7:"handler";s:7:"youtube";}',
  'field_vid_emb_embed_code' => NULL,
  'field_vid_emb_description' => NULL,
))
->values(array(
  'entity_type' => 'node',
  'bundle' => 'vef_content',
  'deleted' => '0',
  'entity_id' => '3273428',
  'revision_id' => '3273428',
  'language' => 'und',
  'delta' => '0',
  'field_vid_emb_video_url' => 'https://vimeo.com/632060933',
  'field_vid_emb_thumbnail_path' => 'public://video_embed_field_thumbnails/vimeo/632060933.',
  'field_vid_emb_video_data' => "a:22:{s:4:\"type\";s:5:\"video\";s:7:\"version\";s:3:\"1.0\";s:13:\"provider_name\";s:5:\"Vimeo\";s:12:\"provider_url\";s:18:\"https://vimeo.com/\";s:5:\"title\";s:20:\"LINK TO LOVE - GUCCI\";s:11:\"author_name\";s:13:\"Sam Goldwater\";s:10:\"author_url\";s:30:\"https://vimeo.com/samgoldwater\";s:7:\"is_plus\";s:1:\"0\";s:12:\"account_type\";s:12:\"live_premium\";s:4:\"html\";s:230:\"<iframe src=\"https://player.vimeo.com/video/632060933?h=cd9ba8ce44&amp;app_id=122963\" width=\"426\" height=\"240\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture\" allowfullscreen title=\"LINK TO LOVE - GUCCI\"></iframe>\";s:5:\"width\";i:426;s:6:\"height\";i:240;s:8:\"duration\";i:154;s:11:\"description\";s:277:\"Conde Nast x Gucci\n\nStarring: Sumire \nDirector: Sam Goldwater\nCG Supervisor: Ben Wilson\nDP: Toshihiko Kizu\nOriginal score: Jo Paterson\nSound design: Tom Jenkins\nProducer: Jude Spour\nJapan Producer: Kiyoshi Maeda\nCreative Director: Modesta Dziautaite\nConde Nast ECD: Becky Mason\";s:13:\"thumbnail_url\";s:96:\"http://i.vimeocdn.com/video/1274369629-7d9c3209bb30623c907adfb047a143d0f1eda2b7db463ea74_295x166\";s:15:\"thumbnail_width\";i:295;s:16:\"thumbnail_height\";i:166;s:30:\"thumbnail_url_with_play_button\";s:213:\"http://i.vimeocdn.com/filter/overlay?src0=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F1274369629-7d9c3209bb30623c907adfb047a143d0f1eda2b7db463ea74_295x166&src1=http%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png\";s:11:\"upload_date\";s:19:\"2021-10-14 10:43:28\";s:8:\"video_id\";i:632060933;s:3:\"uri\";s:17:\"/videos/632060933\";s:7:\"handler\";s:5:\"vimeo\";}",
  'field_vid_emb_embed_code' => NULL,
  'field_vid_emb_description' => NULL,
))
->execute();
