<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('system')
->fields(array(
  'filename' => 'sites/all/modules/contrib/video_embed_field/video_embed_field.module',
  'name' => 'video_embed_field',
  'type' => 'module',
  'owner' => '',
  'status' => '1',
  'bootstrap' => '0',
  'schema_version' => '7010',
  'weight' => '0',
  'info' => 'a:13:{s:4:"name";s:17:"Video Embed Field";s:11:"description";s:63:"Expose a field type for embedding videos from youtube or vimeo.";s:4:"core";s:3:"7.x";s:7:"package";s:5:"Media";s:9:"configure";s:22:"admin/config/media/vef";s:5:"files";a:2:{i:0;s:29:"video_embed_field.migrate.inc";i:1;s:71:"views/handlers/views_embed_field_views_handler_field_thumbnail_path.inc";}s:12:"dependencies";a:2:{i:0;s:6:"ctools";i:1;s:5:"image";}s:7:"version";s:14:"7.x-2.0-beta11";s:7:"project";s:17:"video_embed_field";s:9:"datestamp";s:10:"1441639440";s:5:"mtime";i:1441639440;s:3:"php";s:5:"5.2.4";s:9:"bootstrap";i:0;}',
))
->execute();
