# Schema for configuration files of the Password Policy Username submodule.

password_policy.constraint.plugin.password_username:
  type: password_policy.constraint.plugin
  mapping:
    disallow_username:
      type: boolean
      label: 'Disallow username'
