nys_config.config:
  title: "NY Senate Settings"
  description: "Set Senate session state, and default homepage image"
  route_name: nys_config.config
  parent: system.admin_config
  weight: -1
nys_config.global_tab:
  title: "Global"
  description: "Session state, homepage banner, et al."
