nys_config.config:
  title: "Global NY Senate Settings"
  description: "Set Senate session state, and default homepage image"
  route_name: nys_config.config
  parent: system.admin_config
  weight: -1
