<?php

/**
 * @file
 * Provides alterations for Drupal contrib modules.
 */

use Drupal\Component\Utility\Xss;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function nys_config_preprocess_node__landing(&$variables) {
  $node = $variables['node'];
  $node_override = NULL;
  // Exit the preprocess if not Homepage Landing page.
  if ($node->label() === 'Home') {

    $variables['content']['field_landing_blocks'];

    $session_status = \Drupal::configFactory()->get('nys_config.settings')->get('nys_session_status');
    $node_storage = \Drupal::entityTypeManager()->getStorage('node');

    switch ($session_status) {

      case 'out_session':
        $node_override = $node_storage->loadByProperties([
          'type' => 'landing',
          'title' => 'Home - Out of Session',
        ]);
        break;

      case 'budget_week':
        $node_override = $node_storage->loadByProperties([
          'type' => 'landing',
          'title' => 'Home - Budget Week',
        ]);
        break;

      case 'in_session':
      default:
        // Do nothing. This is default.
        break;
    }

    if (!empty($node_override)) {
      $entity = reset($node_override);
      if (!$entity->field_landing_blocks->isEmpty()) {
        $variables['content']['field_landing_blocks'] = $entity->field_landing_blocks->view('default');
      }
    }

    // Invalidate cache tags on node:homepage.
    $variables['#cache']['tags'][] = 'node:homepage';
  }

}

/**
 * Implements hook_form_alter().
 */
function nys_config_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Session nodes should always have a uStream redirect URL prepopulated.
  if ($form_id == 'node_session_form' && empty($form['field_video_redirect']['widget'][0]['#default_value'])) {
    $redirect_url = \Drupal::configFactory()->get('nys_config.settings')->get('nys_vid_redir_url');
    $form['field_video_redirect']['widget'][0]['value']['#default_value'] = Xss::filter($redirect_url);
  }
}

/**
 * Implements hook_entity_display_build_alter().
 *
 * Directs specified IP's to use an alternate URL for viewing streaming videos.
 */
function nys_config_entity_display_build_alter(&$build, $context) {
  $vid_fields = [
    'field_ustream',
    'field_ustream_url',
    'field_yt',
  ];
  // TO DO: D7 nys_access_permissions_field_attach_view_alter() codes here.
}
