# Schema for configuration files of the Password Policy module.

password_policy.password_policy.*:
  type: config_entity
  label: 'Password Policy'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
      translatable: true
    password_reset:
      type: integer
      label: 'Password reset'
    send_reset_email:
      type: boolean
      label: 'Password reset send email'
    send_pending_email:
      type: sequence
      label: 'Password reset pending days'
      sequence:
        type: integer
        label: 'Password reset pending day'
    langcode:
      type: string
      label: 'Language'
    policy_constraints:
      type: sequence
      label: 'Constraints'
      sequence:
        type: password_policy.constraint.plugin.[id]
        label: 'Constraint'
    show_policy_table:
      type: boolean
      label: 'Show policy table'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'

password_policy.constraint.plugin:
  type: mapping
  label: 'Constraint settings'
  mapping:
    id:
      type: string
      label: 'ID'

password_policy.settings:
  type: config_object
  label: 'Password Policy settings'
  mapping:
    cron_threshold:
      type: integer
      label: 'Cron threshold'
