# Schema for configuration files of the Password Policy Character submodule.

password_policy.constraint.plugin.password_policy_character_constraint:
  type: password_policy.constraint.plugin
  mapping:
    character_count:
      type: integer
    character_type:
      type: string
