baidu_maps.settings:
  type: config_object
  label: 'Geolocation settings'
  mapping:
    key:
      type: string
      label: 'Baidu Maps API Key'

geolocation.map_provider.baidu:
  type: geolocation_map_provider
  label: 'Baidu Maps settings'
  mapping:
    zoom:
      type: string
      label: 'Zoom level'
    height:
      type: string
      label: 'Height value'
    width:
      type: string
      label: 'Width value'
