session_limit.settings:
  type: config_object
  label: Settings
  mapping:
    session_limit_max:
      type: integer
    session_limit_masquerade_ignore:
      type: boolean
    session_limit_behaviour:
      type: integer
    session_limit_logged_out_message_severity:
      type: string
    session_limit_admin_inclusion:
      type: integer
    session_limit_roles:
      type: sequence
      sequence:
        type: integer
