_core:
  default_config_hash: YA7-DHZTafx26xj7TsHR42czXDALmPcX39-Qzh9tbs4
langcode: en
subject: 'One Time Password'
body: "Dear [user:name],\r\n    \r\nYour One Time Passcode for completing your NY Senate TFA Verification is: [user:email_tfa]\r\n    \r\nPlease use this Passcode to complete your transaction. Do not share this Passcode with anyone.\r\n    \r\nThank you,\r\n[site:name] team"
routes: "email_tfa.verifiy\r\nuser.logout"
timeouts: 300
status: false
tracks: globally_enabled
user_one: false
role_exclusion_type: disable_for
ignore_role:
  - constituent
security_code_label_text: 'One-time security code'
security_code_description_text: 'We sent you an email containing your one-time security code. Please enter the code provided to proceed.'
security_code_verify_text: Verify
security_code_interrupt_text: Cancel
verification_succeeded_message: 'One-time security code verification succeeded.'
verification_failed_message: 'One-time security code verification failed.'
verification_interrupted_message: 'One-time security code verification interrupted.'
security_code_length: 8
