_core:
  default_config_hash: gbxsfZiC2MMjzyiqbCPrKXXxlhQDa0pMNs0FSt_33ds
enable: true
address: nys.senate.dev@gmail.com
roles: {  }
allowed: ''
description: true
message: true
mailkeys: ''
mailkeys_skip: ''
