<?php

/**
 * @file
 * Contains rh_paragraphs_library.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function rh_paragraphs_library_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'paragraphs_library_item') {
    return \Drupal::service('rabbit_hole.entity_extender')
      ->getRabbitHoleFields('paragraphs_library_item');
  }
}
