nys_sage.settings:
  type: config_object
  label: 'NYS Sage settings'
  mapping:
    api_key:
      type: string
      label: 'API key to be used with SAGE calls.'
    use_ssl:
      type: boolean
      label: 'Enforces use of HTTP (unchecked) vs HTTPS (checked)'
    ssl_verify_peer:
      type: boolean
      label: 'Unchecking this box will relax certificate chain validation.  This should only be unchecked if absolutely necessary'
    api_endpoint:
      type: string
      label: 'The host and path prefix used to reach the SAGE service.  Protocol, group, and method should not be included.'
    logging:
      type: boolean
      label: 'Turns on detailed logging for SAGE calls.'
    maximum_retention:
      type: integer
      label: 'Maximum number of days to keep SAGE log entries.  Set to zero to keep indefinitely.'
