<?php

/**
 * @file
 * Primary module hooks for NYS Registration module.
 */

use Drupal\nys_registration\Form\RegisterForm;

/**
 * Implements hook_entity_type_alter().
 *
 * Replace the core user registration form with our custom multi-step version.
 */
function nys_registration_entity_type_alter(array &$entity_info): void {
  $route_match = \Drupal::service('current_route_match');
  $current_route_name = $route_match->getRouteName();
  if ($current_route_name !== 'user.admin_create' && $user = ($entity_info['user'] ?? NULL)) {
    $entity_info['user']->setFormClass('default', RegisterForm::class);
  }
}

/**
 * Implements hook_theme().
 */
function nys_registration_theme($existing, $type, $theme, $path) {
  return [
    'register_form_step2' => [
      'render element' => 'form',
    ],
    'register_form_step3' => [
      'render element' => 'form',
    ],
    'register_form_step2_not_found' => [
      'render element' => 'form',
    ],
  ];
}
