<?php

/**
 * @file
 * Primary module hooks for NYS Registration module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use SendGrid\Mail\From;
use SendGrid\Mail\Mail;
use SendGrid\Mail\Personalization;
use SendGrid\Mail\To;

/**
 * Implements hook_entity_type_alter().
 *
 * Replace the core user registration form with our custom multistep version.
 */
function nys_registration_entity_type_alter(array &$entity_types): void {
  if ($user = ($entity_types['user'] ?? NULL)) {
    $user->setFormClass('register', 'Drupal\nys_registration\Form\RegisterForm');
  }
}

/**
 * Implements hook_theme().
 */
function nys_registration_theme($existing, $type, $theme, $path): array {
  return [
    'nys_find_my_senator' => [
      'variables' => [
        'is_anonymous' => TRUE,
        'district' => NULL,
        'district_term' => NULL,
        'map_url' => '',
        'senator' => NULL,
        'address' => [
          'address_line1' => '',
          'address_line2' => '',
          'locality' => '',
          'administrative_area' => '',
          'postal_code' => '',
        ],
      ],
    ],
    'register_form_step2' => [
      'render element' => 'form',
    ],
    'register_form_step3' => [
      'render element' => 'form',
    ],
    'register_form_step2_not_found' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nys_registration_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  $form['#attributes']['class'][] = 'registration-form';

  $form['registration_block_opener'] = [
    '#markup' => '<div class="c-block c-login">',
    '#weight' => 91,
    '#attached' => [
      'library' => [
        'nysenate_theme/registration-form',
      ],
    ],
  ];

  // Get config values.
  $nys_config = \Drupal::configFactory()->get('nys_config.settings');
  $header = $nys_config->get('user_login_header');
  $body = $nys_config->get('user_login_body');
  $footer = $nys_config->get('user_login_footer');

  $form['registration_teaser'] = [
    '#markup' => '<div class="c-login-left"><h3 class="nys-title">' .
      $header . '</h3>' . $body . '<a href="/user/register" ' .
      'class="c-block--btn c-login-create">Create Account</a>' .
      $footer . '</div>',
    '#weight' => 95,
  ];

  $form['login_right_top'] = [
    '#weight' => 96,
    '#markup' => '<div class="c-login-right"><h3 class="nys-title">' .
      t('I already have an account...') . '</h3>',
  ];

  $form['name']['#weight'] = 97;
  $form['pass']['#weight'] = 98;

  $form['actions']['submit'] = [
    '#value' => 'Log in to account',
    '#type' => 'submit',
    '#attributes' => ['class' => ['c-block--btn']],
    '#weight' => 100,
  ];

  $form['reset_password'] = [
    '#type' => 'html_tag',
    '#tag' => 'a',
    '#attributes' => [
      'href' => Url::fromRoute('user.pass')->toString(),
      'id' => 'forgot-password-link',
    ],
    '#value' => 'I forgot my password',
    '#weight' => 101,
  ];

  $form['login_right_bottom'] = [
    '#weight' => 10001,
    '#markup' => '</div>',
  ];

  $form['registration_block_closer'] = [
    '#weight' => 10002,
    '#markup' => '</div>',
  ];

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nys_registration_form_user_pass_reset_alter(&$form, FormStateInterface $form_state, $form_id): void {
  // Redirect the submit action to the custom function.
  $form['#action'] = '/nys' . $form['#action'];
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function nys_registration_menu_local_tasks_alter(&$data, $route_name, &$cacheability): void {
  if ($route_name === 'user.login') {
    unset($data['tabs']);
  }
}
