<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.10 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('file_metadata', array(
  'fields' => array(
    'fid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'name' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
    ),
    'value' => array(
      'type' => 'blob',
      'not null' => FALSE,
      'size' => 'big',
    ),
  ),
  'primary key' => array(
    'fid',
    'name',
  ),
  'mysql_character_set' => 'utf8',
));

$connection->insert('file_metadata')
->fields(array(
  'fid',
  'name',
  'value',
))
->values(array(
  'fid' => '1',
  'name' => 'height',
  'value' => 'i:720;',
))
->values(array(
  'fid' => '1',
  'name' => 'width',
  'value' => 'i:1280;',
))
->values(array(
  'fid' => '2',
  'name' => 'height',
  'value' => 'i:960;',
))
->values(array(
  'fid' => '2',
  'name' => 'width',
  'value' => 'i:720;',
))
->values(array(
  'fid' => '3',
  'name' => 'height',
  'value' => 'i:720;',
))
->values(array(
  'fid' => '3',
  'name' => 'width',
  'value' => 'i:1280;',
))
->values(array(
  'fid' => '7',
  'name' => 'height',
  'value' => 'i:400;',
))
->values(array(
  'fid' => '7',
  'name' => 'width',
  'value' => 'i:640;',
))
->values(array(
  'fid' => '10',
  'name' => 'height',
  'value' => 'i:400;',
))
->values(array(
  'fid' => '10',
  'name' => 'width',
  'value' => 'i:640;',
))
->execute();
