<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.10 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('file_display', array(
  'fields' => array(
    'name' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
    ),
    'weight' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ),
    'status' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'settings' => array(
      'type' => 'blob',
      'not null' => FALSE,
      'size' => 'big',
    ),
  ),
  'primary key' => array(
    'name',
  ),
  'mysql_character_set' => 'utf8',
));

$connection->insert('file_display')
->fields(array(
  'name',
  'weight',
  'status',
  'settings',
))
->values(array(
  'name' => 'image__default__file_field_file_default',
  'weight' => '50',
  'status' => '1',
  'settings' => 's:0:"";',
))
->values(array(
  'name' => 'image__default__file_field_file_download_link',
  'weight' => '0',
  'status' => '0',
  'settings' => 'a:1:{s:4:"text";s:20:"Download [file:name]";}',
))
->values(array(
  'name' => 'image__default__file_field_file_table',
  'weight' => '0',
  'status' => '0',
  'settings' => 'N;',
))
->values(array(
  'name' => 'image__default__file_field_file_url_plain',
  'weight' => '0',
  'status' => '0',
  'settings' => 'N;',
))
->values(array(
  'name' => 'image__default__file_field_image',
  'weight' => '48',
  'status' => '1',
  'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
))
->values(array(
  'name' => 'image__default__file_field_media_large_icon',
  'weight' => '0',
  'status' => '0',
  'settings' => 'a:1:{s:11:"image_style";s:0:"";}',
))
->values(array(
  'name' => 'image__wysiwyg__file_field_file_default',
  'weight' => '-48',
  'status' => '1',
  'settings' => 'N;',
))
->values(array(
  'name' => 'image__wysiwyg__file_field_file_download_link',
  'weight' => '-50',
  'status' => '0',
  'settings' => 'a:1:{s:4:"text";s:20:"Download [file:name]";}',
))
->values(array(
  'name' => 'image__wysiwyg__file_field_file_table',
  'weight' => '-46',
  'status' => '0',
  'settings' => 'N;',
))
->values(array(
  'name' => 'image__wysiwyg__file_field_file_url_plain',
  'weight' => '-45',
  'status' => '0',
  'settings' => 'N;',
))
->values(array(
  'name' => 'image__wysiwyg__file_field_image',
  'weight' => '-49',
  'status' => '1',
  'settings' => 'a:2:{s:11:"image_style";s:5:"large";s:10:"image_link";s:0:"";}',
))
->values(array(
  'name' => 'image__wysiwyg__file_field_media_large_icon',
  'weight' => '-47',
  'status' => '0',
  'settings' => 'a:1:{s:11:"image_style";s:0:"";}',
))
->execute();
