<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.10 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('search_total', array(
  'fields' => array(
    'word' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '50',
      'default' => '',
    ),
    'count' => array(
      'type' => 'float',
      'not null' => FALSE,
      'size' => 'normal',
    ),
  ),
  'primary key' => array(
    'word',
  ),
  'mysql_character_set' => 'utf8',
));

$connection->insert('search_total')
->fields(array(
  'word',
  'count',
))
->values(array(
  'word' => 'aliquam',
  'count' => '0.176091',
))
->values(array(
  'word' => 'aliquet',
  'count' => '0.30103',
))
->values(array(
  'word' => 'amet',
  'count' => '0.176091',
))
->values(array(
  'word' => 'ante',
  'count' => '0.178664',
))
->values(array(
  'word' => 'aptent',
  'count' => '0.30103',
))
->values(array(
  'word' => 'arcu',
  'count' => '0.1035',
))
->values(array(
  'word' => 'article',
  'count' => '0.00827253',
))
->values(array(
  'word' => 'auctor',
  'count' => '0.30103',
))
->values(array(
  'word' => 'auctorproin',
  'count' => '0.30103',
))
->values(array(
  'word' => 'augue',
  'count' => '0.124939',
))
->values(array(
  'word' => 'bibendum',
  'count' => '0.30103',
))
->values(array(
  'word' => 'blandit',
  'count' => '0.102239',
))
->values(array(
  'word' => 'blue',
  'count' => '0.0147233',
))
->values(array(
  'word' => 'class',
  'count' => '0.30103',
))
->values(array(
  'word' => 'condimentum',
  'count' => '0.30103',
))
->values(array(
  'word' => 'congue',
  'count' => '0.18123',
))
->values(array(
  'word' => 'consectetur',
  'count' => '0.124939',
))
->values(array(
  'word' => 'consequat',
  'count' => '0.0824382',
))
->values(array(
  'word' => 'conubia',
  'count' => '0.30103',
))
->values(array(
  'word' => 'curabitur',
  'count' => '0.30103',
))
->values(array(
  'word' => 'cursus',
  'count' => '0.1863',
))
->values(array(
  'word' => 'dapibus',
  'count' => '0.18315',
))
->values(array(
  'word' => 'diam',
  'count' => '0.0989888',
))
->values(array(
  'word' => 'dictum',
  'count' => '0.30103',
))
->values(array(
  'word' => 'dignissim',
  'count' => '0.176091',
))
->values(array(
  'word' => 'donec',
  'count' => '0.185529',
))
->values(array(
  'word' => 'dui',
  'count' => '0.30103',
))
->values(array(
  'word' => 'duis',
  'count' => '0.30103',
))
->values(array(
  'word' => 'egestas',
  'count' => '0.125929',
))
->values(array(
  'word' => 'eget',
  'count' => '0.184484',
))
->values(array(
  'word' => 'egetmorbi',
  'count' => '0.30103',
))
->values(array(
  'word' => 'eleifend',
  'count' => '0.30103',
))
->values(array(
  'word' => 'elementum',
  'count' => '0.124939',
))
->values(array(
  'word' => 'embed',
  'count' => '0.0163904',
))
->values(array(
  'word' => 'erat',
  'count' => '0.124939',
))
->values(array(
  'word' => 'eros',
  'count' => '0.134177',
))
->values(array(
  'word' => 'etiam',
  'count' => '0.30103',
))
->values(array(
  'word' => 'euismod',
  'count' => '0.30103',
))
->values(array(
  'word' => 'facilisis',
  'count' => '0.30103',
))
->values(array(
  'word' => 'faucibus',
  'count' => '0.30103',
))
->values(array(
  'word' => 'felis',
  'count' => '0.141307',
))
->values(array(
  'word' => 'fermentum',
  'count' => '0.176091',
))
->values(array(
  'word' => 'feugiat',
  'count' => '0.176091',
))
->values(array(
  'word' => 'finibus',
  'count' => '0.30103',
))
->values(array(
  'word' => 'fringilla',
  'count' => '0.30103',
))
->values(array(
  'word' => 'fusce',
  'count' => '0.30103',
))
->values(array(
  'word' => 'gravida',
  'count' => '0.103814',
))
->values(array(
  'word' => 'hendrerit',
  'count' => '0.30103',
))
->values(array(
  'word' => 'himenaeos',
  'count' => '0.30103',
))
->values(array(
  'word' => 'iaculis',
  'count' => '0.138885',
))
->values(array(
  'word' => 'image',
  'count' => '0.00827253',
))
->values(array(
  'word' => 'imperdiet',
  'count' => '0.30103',
))
->values(array(
  'word' => 'inceptos',
  'count' => '0.30103',
))
->values(array(
  'word' => 'integer',
  'count' => '0.176091',
))
->values(array(
  'word' => 'interdum',
  'count' => '0.0834618',
))
->values(array(
  'word' => 'ipsum',
  'count' => '0.193139',
))
->values(array(
  'word' => 'justo',
  'count' => '0.188745',
))
->values(array(
  'word' => 'lacinia',
  'count' => '0.176091',
))
->values(array(
  'word' => 'laoreet',
  'count' => '0.30103',
))
->values(array(
  'word' => 'lectus',
  'count' => '0.124939',
))
->values(array(
  'word' => 'leo',
  'count' => '0.176091',
))
->values(array(
  'word' => 'libero',
  'count' => '0.30103',
))
->values(array(
  'word' => 'ligula',
  'count' => '0.30103',
))
->values(array(
  'word' => 'litora',
  'count' => '0.30103',
))
->values(array(
  'word' => 'lobortis',
  'count' => '0.0829639',
))
->values(array(
  'word' => 'lorem',
  'count' => '0.30103',
))
->values(array(
  'word' => 'luctus',
  'count' => '0.18315',
))
->values(array(
  'word' => 'maecenas',
  'count' => '0.30103',
))
->values(array(
  'word' => 'magna',
  'count' => '0.30103',
))
->values(array(
  'word' => 'massa',
  'count' => '0.0994485',
))
->values(array(
  'word' => 'mattis',
  'count' => '0.30103',
))
->values(array(
  'word' => 'mauris',
  'count' => '0.182183',
))
->values(array(
  'word' => 'maximus',
  'count' => '0.30103',
))
->values(array(
  'word' => 'media',
  'count' => '0.0163904',
))
->values(array(
  'word' => 'metus',
  'count' => '0.134852',
))
->values(array(
  'word' => 'molestie',
  'count' => '0.176091',
))
->values(array(
  'word' => 'mollis',
  'count' => '0.187564',
))
->values(array(
  'word' => 'morbi',
  'count' => '0.187855',
))
->values(array(
  'word' => 'nam',
  'count' => '0.30103',
))
->values(array(
  'word' => 'nec',
  'count' => '0.126074',
))
->values(array(
  'word' => 'neque',
  'count' => '0.178954',
))
->values(array(
  'word' => 'nibh',
  'count' => '0.1863',
))
->values(array(
  'word' => 'nisi',
  'count' => '0.184747',
))
->values(array(
  'word' => 'nisl',
  'count' => '0.30103',
))
->values(array(
  'word' => 'non',
  'count' => '0.0866921',
))
->values(array(
  'word' => 'nostra',
  'count' => '0.30103',
))
->values(array(
  'word' => 'nullam',
  'count' => '0.12821',
))
->values(array(
  'word' => 'nunc',
  'count' => '0.0998785',
))
->values(array(
  'word' => 'odio',
  'count' => '0.30103',
))
->values(array(
  'word' => 'only',
  'count' => '0.0163904',
))
->values(array(
  'word' => 'orci',
  'count' => '0.30103',
))
->values(array(
  'word' => 'ornare',
  'count' => '0.30103',
))
->values(array(
  'word' => 'pellentesque',
  'count' => '0.124939',
))
->values(array(
  'word' => 'per',
  'count' => '0.176091',
))
->values(array(
  'word' => 'pharetra',
  'count' => '0.176091',
))
->values(array(
  'word' => 'phasellus',
  'count' => '0.186808',
))
->values(array(
  'word' => 'placerat',
  'count' => '0.1863',
))
->values(array(
  'word' => 'png',
  'count' => '0.0147233',
))
->values(array(
  'word' => 'porta',
  'count' => '0.30103',
))
->values(array(
  'word' => 'porttitor',
  'count' => '0.129831',
))
->values(array(
  'word' => 'posuere',
  'count' => '0.190692',
))
->values(array(
  'word' => 'potenti',
  'count' => '0.30103',
))
->values(array(
  'word' => 'praesent',
  'count' => '0.186808',
))
->values(array(
  'word' => 'pretium',
  'count' => '0.30103',
))
->values(array(
  'word' => 'proin',
  'count' => '0.176091',
))
->values(array(
  'word' => 'pulvinar',
  'count' => '0.102597',
))
->values(array(
  'word' => 'purus',
  'count' => '0.30103',
))
->values(array(
  'word' => 'quam',
  'count' => '0.30103',
))
->values(array(
  'word' => 'quis',
  'count' => '0.09691',
))
->values(array(
  'word' => 'quisque',
  'count' => '0.186044',
))
->values(array(
  'word' => 'rhoncus',
  'count' => '0.30103',
))
->values(array(
  'word' => 'risus',
  'count' => '0.187081',
))
->values(array(
  'word' => 'rutrum',
  'count' => '0.193346',
))
->values(array(
  'word' => 'sagittis',
  'count' => '0.19011',
))
->values(array(
  'word' => 'sapien',
  'count' => '0.0804095',
))
->values(array(
  'word' => 'sapiensed',
  'count' => '0.30103',
))
->values(array(
  'word' => 'scelerisque',
  'count' => '0.191015',
))
->values(array(
  'word' => 'sed',
  'count' => '0.0677899',
))
->values(array(
  'word' => 'sem',
  'count' => '0.30103',
))
->values(array(
  'word' => 'semper',
  'count' => '0.30103',
))
->values(array(
  'word' => 'single',
  'count' => '0.0163904',
))
->values(array(
  'word' => 'sit',
  'count' => '0.176091',
))
->values(array(
  'word' => 'sociosqu',
  'count' => '0.30103',
))
->values(array(
  'word' => 'sodales',
  'count' => '0.176091',
))
->values(array(
  'word' => 'suscipit',
  'count' => '0.186555',
))
->values(array(
  'word' => 'suspendisse',
  'count' => '0.137875',
))
->values(array(
  'word' => 'taciti',
  'count' => '0.30103',
))
->values(array(
  'word' => 'tempor',
  'count' => '0.131649',
))
->values(array(
  'word' => 'tincidunt',
  'count' => '0.30103',
))
->values(array(
  'word' => 'torquent',
  'count' => '0.30103',
))
->values(array(
  'word' => 'tortor',
  'count' => '0.30103',
))
->values(array(
  'word' => 'tristique',
  'count' => '0.127893',
))
->values(array(
  'word' => 'turpis',
  'count' => '0.101514',
))
->values(array(
  'word' => 'ullamcorper',
  'count' => '0.18315',
))
->values(array(
  'word' => 'ultricies',
  'count' => '0.30103',
))
->values(array(
  'word' => 'vehicula',
  'count' => '0.30103',
))
->values(array(
  'word' => 'vel',
  'count' => '0.0466913',
))
->values(array(
  'word' => 'velit',
  'count' => '0.179244',
))
->values(array(
  'word' => 'vestibulum',
  'count' => '0.176091',
))
->values(array(
  'word' => 'vitae',
  'count' => '0.0969685',
))
->values(array(
  'word' => 'vivamus',
  'count' => '0.176091',
))
->values(array(
  'word' => 'volutpat',
  'count' => '0.178954',
))
->values(array(
  'word' => 'with',
  'count' => '0.00827253',
))
->execute();
