<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.10 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('wysiwyg', array(
  'fields' => array(
    'format' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
    ),
    'editor' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'settings' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
  ),
  'primary key' => array(
    'format',
  ),
  'mysql_character_set' => 'utf8',
));

$connection->insert('wysiwyg')
->fields(array(
  'format',
  'editor',
  'settings',
))
->values(array(
  'format' => 'filtered_html',
  'editor' => 'ckeditor',
  'settings' => 'a:18:{s:7:"buttons";a:2:{s:7:"default";a:12:{s:4:"Bold";i:1;s:6:"Italic";i:1;s:9:"Underline";i:1;s:6:"Strike";i:1;s:12:"BulletedList";i:1;s:12:"NumberedList";i:1;s:4:"Link";i:1;s:6:"Unlink";i:1;s:10:"Blockquote";i:1;s:6:"Source";i:1;s:11:"SpecialChar";i:1;s:8:"Maximize";i:1;}s:6:"drupal";a:1:{s:5:"media";i:1;}}s:5:"theme";s:0:"";s:8:"language";s:2:"en";s:15:"toolbarLocation";s:3:"top";s:14:"resize_enabled";i:1;s:24:"default_toolbar_grouping";i:0;s:24:"simple_source_formatting";i:0;s:8:"acf_mode";s:1:"0";s:19:"acf_allowed_content";s:0:"";s:11:"css_setting";s:5:"theme";s:9:"css_theme";s:5:"seven";s:8:"css_path";s:0:"";s:9:"stylesSet";s:0:"";s:13:"block_formats";s:32:"p,address,pre,h2,h3,h4,h5,h6,div";s:21:"forcePasteAsPlainText";i:0;s:26:"pasteFromWordPromptCleanup";i:0;s:29:"pasteFromWordRemoveFontStyles";i:1;s:20:"_profile_preferences";a:5:{s:7:"default";i:1;s:11:"user_choose";i:0;s:11:"show_toggle";i:1;s:16:"add_to_summaries";i:1;s:7:"version";s:17:"4.12.1.64749bb245";}}',
))
->execute();
