menu_token.link_configuration_storage.*:
  type: config_entity
  label: 'Link configuration storage config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    linkid:
      type: string
      label: 'linkid'
    configurationSerialized:
      type: string
      label: 'configurationSerialized'
