<?php

/**
 * @file
 * Module nys_openleg.
 */

/**
 * Implements hook_theme().
 */
function nys_openleg_theme(): array {
  return [
    'nys_openleg_testing' => [
      'variables' => ['debug' => [], 'breadcrumbs' => []],
    ],
    'nys_openleg_result_head_breadcrumbs' => [
      'variables' => ['breadcrumbs' => []],
    ],
    'nys_openleg_result_head_nav' => [
      'variables' => ['nav' => []],
    ],
    'nys_openleg_result_head_title' => [
      'variables' => ['title' => NULL],
    ],
    'nys_openleg_result_item' => [
      'variables' => [
        'url' => NULL,
        'name' => NULL,
        'description' => NULL,
        'item_type' => 'item',
      ],
    ],
    'nys_openleg_result' => [
      'variables' => [
        'title_parts' => NULL,
        'title' => NULL,
        'share_path' => NULL,
        'mail_link' => NULL,
        'list_items' => NULL,
        'entry_text' => NULL,
        'breadcrumbs' => NULL,
        'nav' => NULL,
        'history' => NULL,
        'search' => NULL,
        'deprecation_warning' => NULL,
        'debug' => NULL,
      ],
    ],
    'nys_openleg_search_results' => [
      'variables' => [
        'search_form' => NULL,
        'term' => NULL,
        'results' => [],
        'pager' => NULL,
      ],
    ],
    'nys_openleg_search_result' => [
      'variables' => [
        'name' => NULL,
        'title' => NULL,
        'url' => NULL,
        'snippets' => [],
      ],
    ],
    'nys_openleg_not_found' => [
      'variables' => ['additional' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function nys_openleg_preprocess_block__nys_blocks_bythe_numbers(&$variables) {
  $content = $variables['elements']['content'];
  $variables['facts_title'] = $content['#first_year'] . '-' . $content['#second_year'] . ' by the numbers';

  $legislative_session = date("Y", strtotime("now"));

  if (($legislative_session % 2) == 0) {
    $legislative_session--;
  }

  // @todo Verify logic to become dynamic year
  $openApiService = \Drupal::service('manager.openleg_api');

  $awaiting = $openApiService->getSearch('bill', 'session:' . '2021' . ' AND status.statusType:DELIVERED_TO_GOV');
  $signed = $openApiService->getSearch('bill', 'session:' . '2021' . ' AND status.statusType:SIGNED_BY_GOV');
  $vetoed = $openApiService->getSearch('bill', 'session:' . '2021' . ' AND status.statusType:VETOED');

  $variables['facts'] = [
    [
      'link' => '/search/legislation?searched=true&type=f_bill&bill_session_year=' . $content['#session_year'] . '&bill_status=SIGNED_BY_GOV&page=1',
      'statistic' => $signed->total,
      'description' => 'Bills Signed into Law',
      'status' => 'signed',
    ],
    [
      'link' => '/search/legislation?searched=true&type=f_bill&bill_session_year=' . $content['#session_year'] . '&bill_status=DELIVERED_TO_GOV&page=1',
      'statistic' => $awaiting->total,
      'description' => 'BILLS AWAITING THE GOVERNOR’S SIGNATURE',
      'status' => 'waiting',
    ],
    [
      'link' => '/search/legislation?searched=true&type=f_bill&bill_session_year=' . $content['#session_year'] . '&bill_status=VETOED&page=1',
      'statistic' => $vetoed->total,
      'description' => 'BILLS VETOED BY THE GOVERNOR',
      'status' => 'vetoed',
    ],
  ];
}
