# Schema for configuration files of the Password Policy Delay submodule.

password_policy.constraint.plugin.password_policy_delay_constraint:
  type: password_policy.constraint.plugin
  mapping:
    delay:
      type: integer
      label: 'Hours until next password reset may be performed.'
