<?php

/**
 * @file
 * Provides a subscription entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function nys_subscriptions_theme() {
  return [
    'subscription' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for subscription templates.
 *
 * Default template: subscription.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the subscription information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_subscription(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
