views.style.chart:
  type: views_style
  label: 'Chart'
  mapping:
    title:
      type: label
      label: 'Chart title'
    xaxis_title:
      type: label
      label: 'Horizontal axis title'
    yaxis_title:
      type: label
      label: 'Vertical axis title'

views.display.chart_extension:
  type: views_display
  label: 'Attachment display options'
