password_policy.constraint.plugin.consecutive:
  type: password_policy.constraint.plugin
  mapping:
    max_consecutive_characters:
      type: integer
      label: 'Maximum consecutive character count'
