geolocation.data_provider.geolocation_gpx:
  type: geolocation_data_provider
  label: 'GPX field'
  mapping:
    return_track_locations:
      type: boolean
    return_waypoint_locations:
      type: boolean
    return_tracks:
      type: boolean
    return_waypoints:
      type: boolean
    track_stroke_color:
      type: string
    track_stroke_color_randomize:
      type: boolean
    track_stroke_width:
      type: integer
    track_stroke_opacity:
      type: float
