<?php

/**
 * @file
 * Contains custom code for Bill Votes module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_theme().
 */
function nys_bill_vote_theme($existing, $type, $theme, $path): array {
  return [
    'nys_bill_vote_management_bills' => [
      'variables' => [
        'sponsored_bills' => NULL,
        'bill_messages' => NULL,
      ],
    ],
    'nys_bill_vote_summary_highchart' => [
      'variables' => [
        'nid' => NULL,
        'title' => NULL,
        'summary' => NULL,
        'issues_tid' => NULL,
        'issues' => NULL,
        'in_district_aye' => NULL,
        'in_district_nay' => NULL,
        'out_district_aye' => NULL,
        'out_district_nay' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function nys_bill_vote_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $type = $entity->bundle();

  // If the entity is a bill, get the form and save it to content.
  $route_node = \Drupal::routeMatch()->getParameter('node');
  if ($type == 'bill') {
    $bill_vote_form_settings = [
      'entity_type' => $entity->bundle(),
      'entity_id' => $entity->id(),
      'is_embed' => empty($route_node) || $route_node->id() !== $entity->id(),
      'simple_mode' => FALSE,
    ];

    if ($display->getComponent('vote_widget')) {
      $build['vote_widget'] = [
        'form' => \Drupal::formBuilder()->getForm('Drupal\nys_bill_vote\Form\BillVoteWidgetForm', $bill_vote_form_settings),
      ];
    }

    if ($display->getComponent('vote_widget_simple')) {
      $bill_vote_form_settings['simple_mode'] = TRUE;
      $build['vote_widget'] = [
        'form' => \Drupal::formBuilder()->getForm('Drupal\nys_bill_vote\Form\BillVoteWidgetForm', $bill_vote_form_settings),
      ];
    }
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function nys_bill_vote_entity_extra_field_info() {
  $extra = [];

  foreach (NodeType::loadMultiple() as $bundle) {
    if ($bundle->id() == 'bill') {
      $extra['node'][$bundle->id()]['display']['vote_widget'] = [
        'label' => t('Vote Widget'),
        'description' => t('Vote widget from nys_bill_vote'),
        'weight' => 100,
        'visible' => TRUE,
      ];

      $extra['node'][$bundle->id()]['display']['vote_widget_simple'] = [
        'label' => t('Vote Widget Simple'),
        'description' => t('Simple vote widget from nys_bill_vote'),
        'weight' => 100,
        'visible' => TRUE,
      ];
    }
  }

  return $extra;
}
