<?php

/**
 * @file
 * Contains custom code for Bill Votes module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_theme().
 */
function nys_bill_vote_theme($existing, $type, $theme, $path): array {
  return [
    'nys_bill_vote_management_bills' => [
      'variables' => [
        'sponsored_bills' => NULL,
        'bill_messages' => NULL,
      ],
    ],
    'nys_bill_vote_summary_highchart' => [
      'variables' => [
        'nid' => NULL,
        'title' => NULL,
        'summary' => NULL,
        'issues_tid' => NULL,
        'issues' => NULL,
        'in_district_aye' => NULL,
        'in_district_nay' => NULL,
        'out_district_aye' => NULL,
        'out_district_nay' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function nys_bill_vote_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $type = $entity->bundle();

  // If the entity is a bill, get the form and save it to content.
  $route_node = \Drupal::routeMatch()->getParameter('node');
  if ($type == 'bill') {
    $is_embed = empty($route_node) || $route_node->id() !== $entity->id();

    if ($display->getComponent('vote_widget')) {
      $build['vote_widget'] = [
        '#lazy_builder' => [
          'nys_bill_vote.vote_widget_lazy_builder:renderVoteWidget',
          [(int) $entity->id(), $is_embed, FALSE],
        ],
        '#create_placeholder' => TRUE,
      ];
    }

    if ($display->getComponent('vote_widget_simple')) {
      $build['vote_widget'] = [
        '#lazy_builder' => [
          'nys_bill_vote.vote_widget_lazy_builder:renderVoteWidget',
          [(int) $entity->id(), $is_embed, TRUE],
        ],
        '#create_placeholder' => TRUE,
      ];
    }
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function nys_bill_vote_entity_extra_field_info() {
  $extra = [];
  $extra['node']['bill']['display']['vote_widget'] = [
    'label' => t('Vote Widget'),
    'description' => t('Vote widget from nys_bill_vote'),
    'weight' => 100,
    'visible' => TRUE,
  ];
  $extra['node']['bill']['display']['vote_widget_simple'] = [
    'label' => t('Vote Widget Simple'),
    'description' => t('Simple vote widget from nys_bill_vote'),
    'weight' => 100,
    'visible' => TRUE,
  ];
  return $extra;
}
