views.field.geolocation_geometry_field_proximity:
  type: views.field.geolocation_field_proximity
  label: 'Geometry Proximity Field'

views.filter.geolocation_geometry_filter_boundary:
  type: views.filter.geolocation_filter_boundary
  label: 'Geometry Boundary Filter'

views.filter_value.geolocation_geometry_filter_proximity:
  type: views.filter_value.geolocation_filter_proximity
  label: 'Group by Geo Distance'

views.filter.group_item.geolocation_geometry_filter_proximity:
  type: views_filter_group_item
  mapping:
    value:
      type: views.filter_value.numeric

views.argument.geolocation_geometry_argument_proximity:
  type: views_argument
  label: 'Geometry Proximity Argument'

views.argument.geolocation_geometry_argument_boundary:
  type: views_argument
  label: 'Geometry Boundary Argument'
