geolocation.data_provider.geolocation_geometry:
  type: geolocation_data_provider
  label: 'Geometry field'
  mapping:
    stroke_color:
      type: string
    stroke_color_randomize:
      type: boolean
    stroke_width:
      type: integer
    stroke_opacity:
      type: float
    fill_color:
      type: string
    fill_color_randomize:
      type: boolean
    fill_opacity:
      type: float
