webform_views_extras.webform_submission_relationships.*:
  type: config_entity
  label: 'Webform submission relationships config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    content_entity_type_id:
      type: string
      label: 'Content entity type Id'
