email_registration_username.settings:
  type: config_object
  label: 'Email registration username config'
  mapping:
    username_display_override_mode:
      type: string
      label: 'Username Display Override Mode'
    username_display_custom:
      type: label
      label: 'Username display custom'
