<?php

/**
 * @file
 * Contains custom module logic for NYS Senator Dashboard.
 */

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\flag\Plugin\Flag\EntityFlagType;
use Drupal\node\NodeInterface;

/**
 * Implements hook_query_TAG_alter().
 *
 * Ensures views with the "senators_constituents_only" tag only display profiles
 * linked to the current user's active managed senator's districts.
 */
function nys_senator_dashboard_query_senators_constituents_only_alter(AlterableInterface $query) {
  // Get active managed senator.
  $senator_term = \Drupal::service('nys_senator_dashboard.managed_senators_handler')
    ->getActiveSenator(FALSE);
  if (empty($senator_term)) {
    $query->alwaysFalse();
    return;
  }

  // Get senator's districts.
  $managed_district_ids = [];
  try {
    $senator_districts = \Drupal::entityTypeManager()
      ->getStorage('taxonomy_term')
      ->loadByProperties([
        'vid' => 'districts',
        'field_senator' => $senator_term->id(),
      ]);
  }
  catch (\Throwable $e) {
    $query->alwaysFalse();
    return;
  }
  foreach ($senator_districts as $senator_district) {
    $managed_district_ids[] = $senator_district->id();
  }
  if (empty($managed_district_ids)) {
    $query->alwaysFalse();
    return;
  }

  // Get the views table alias corresponding to the users_field_data table
  // (could be users_field_data_1, etc.).
  $table_aliases = $query->getTables();
  $user_table_alias = null;
  foreach ($table_aliases as $alias => $table_info) {
    if ($table_info['table'] === 'users_field_data') {
      $user_table_alias = $alias;
      break;
    }
  }
  if (!$user_table_alias) {
    $query->alwaysFalse();
    return;
  }

  // Ensure the users being fetched are within the user's active managed
  // senator's districts.
  $query->leftJoin(
    'user__field_district',
    'ufd',
    "{$user_table_alias}.uid = ufd.entity_id"
  );
  $query->condition('ufd.field_district_target_id', $managed_district_ids, 'IN');
}

/**
 * Implements hook_theme().
 */
function nys_senator_dashboard_theme() {
  return [
    'nys_senator_dashboard_header' => [
      'variables' => [
        'senator_image_url' => '',
        'breadcrumbs' => '',
        'header_title' => '',
        'header_blurb' => '',
        'homepage_url' => '',
      ],
    ],
    'nys_senator_dashboard_constituent_engagement' => [
      'variables' => [
        'items' => [],
        'title' => '',
      ],
    ],
    'nys_senator_dashboard__set_active_senator_menu' => [
      'variables' => [
        'mode' => '',
        'active_senator_links' => [],
      ],
    ],
    'menu__senator_dashboard' => [
      'variables' => [
        'mode' => '',
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function nys_senator_dashboard_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (str_starts_with($form_id, 'views_form_senator_dashboard_constituents_')) {
    // Hide additional footer bulk operation button.
    $form['actions']['#access'] = FALSE;
  }
}

/**
 * Implements hook_views_data().
 */
function nys_senator_dashboard_views_data() {
  $data['users']['votingapi_vote']['relationship'] = [
    'title' => t('User votes'),
    'label' => t('Vote entity'),
    'group' => 'Users',
    'help' => t('Reference to vote entities by a user.'),
    'id' => 'standard',
    'base' => 'votingapi_vote',
    'base field' => 'user_id',
    'field' => 'uid',
  ];
  $data['users']['flagging']['relationship'] = [
    'title' => t('User flaggings'),
    'label' => t('Flagging entity'),
    'group' => 'Users',
    'help' => t('Reference to flagging entities by a user.'),
    'id' => 'flag_relationship',
    'base' => 'flagging',
    'base field' => 'uid',
    'field' => 'uid',
  ];
  $data['users']['nys_senator_dashboard_contextual_filter_flag_link'] = [
    'title' => t('NYS Senator Dashboard: Flag link (from issue ID contextual filter)'),
    'help' => t('Displays a flag link based on an issue ID context filter value.'),
    'field' => [
      'id' => 'nys_senator_dashboard_contextual_filter_flag_link',
    ],
  ];
  $data['users']['nys_senator_dashboard_contextual_filter_webform_id'] = [
    'title' => t('NYS Senator Dashboard: Webform ID (from entity ID contextual filter)'),
    'help' => t('Displays the Webform ID based on the parent entity ID from the context filter value.'),
    'field' => [
      'id' => 'nys_senator_dashboard_contextual_filter_webform_id',
    ],
  ];
  $data['node']['nys_senator_dashboard_active_senator_sponsor_filter'] = [
    'title' => t('NYS Senator Dashboard: Active senator sponsor filter'),
    'help' => t('Filter bills to those sponsored or co-sponsored by the active senator.'),
    'filter' => [
      'id' => 'nys_senator_dashboard_active_senator_sponsor_filter',
    ],
  ];
  $data['node__field_senator_multiref']['nys_senator_dashboard_active_senator_filter'] = [
    'title' => t('NYS Senator Dashboard: Active managed senator filter'),
    'help' => t("Filter nodes to those linked to the user's active managed senator."),
    'filter' => [
      'id' => 'nys_senator_dashboard_active_senator_filter',
      'field' => 'field_senator_multiref_target_id',
      'group' => t('Content'),
    ],
  ];
  $data['taxonomy_term_data']['nys_senator_dashboard_active_senator_used_issues'] = [
    'title' => t('NYS Senator Dashboard: Active senator used issues filter'),
    'help' => t('Filter issues to those used in content (Articles, Press Releases, etc.) by the active senator.'),
    'filter' => [
      'id' => 'nys_senator_dashboard_active_senator_used_issues',
    ],
  ];
  $data['taxonomy_term_data']['nys_senator_dashboard_issue_followers_count_sort'] = [
    'title' => t('NYS Senator Dashboard: Issue followers'),
    'help' => t('Sort taxonomy terms by the number of follow_issue flaggings.'),
    'sort' => [
      'id' => 'nys_senator_dashboard_issue_followers_count_sort',
    ],
  ];
  return $data;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function nys_senator_dashboard_entity_extra_field_info() {
  $extra = [];
  $flag_service = \Drupal::service('flag');
  $flags = $flag_service->getAllFlags();

  /** @var \Drupal\flag\FlagInterface $flag */
  foreach ($flags as $flag) {
    $flag_type_plugin = $flag->getFlagTypePlugin();
    if (!($flag_type_plugin instanceof EntityFlagType)) {
      continue;
    }

    $flaggable_bundles = $flag->getApplicableBundles();
    foreach ($flaggable_bundles as $bundle_name) {
      $extra[$flag->getFlaggableEntityTypeId()][$bundle_name]['display']['nys_senator_dashboard_flag_link_' . $flag->id()] = [
        'label' => t('NYS Senator Dashboard: Entity label Flag link: %title', ['%title' => $flag->label()]),
        'description' => t('A custom flag link that uses the entity label as the link text.'),
        'weight' => 10,
        'visible' => FALSE,
      ];

      $extra[$flag->getFlaggableEntityTypeId()][$bundle_name]['display']['nys_senator_dashboard_flag_count_' . $flag->id()] = [
        'label' => t('NYS Senator Dashboard: Flag count: %title', ['%title' => $flag->label()]),
        'description' => t('A custom field that displays the total flagging count on an entity.'),
        'weight' => 11,
        'visible' => FALSE,
      ];

      $extra[$flag->getFlaggableEntityTypeId()][$bundle_name]['display']['nys_senator_dashboard_district_flag_count_' . $flag->id()] = [
        'label' => t('NYS Senator Dashboard: In / out district flagging counts: %title', ['%title' => $flag->label()]),
        'description' => t('A custom field that displays in / out district flagging counts.'),
        'weight' => 12,
        'visible' => FALSE,
      ];
    }
  }

  $extra['node']['petition']['display']['nys_senator_dashboard_link_to_constituents_list'] = [
    'label' => t('NYS Senator Dashboard: Link to constituents list'),
    'description' => t('Displays a link to the constituents list.'),
    'weight' => 13,
    'visible' => FALSE,
  ];

  $nys_senator_dashboard_status = [
    'label' => t('NYS Senator Dashboard: Active status'),
    'description' => t('Displays the nodes status as Active or Inactive.'),
    'weight' => 14,
    'visible' => FALSE,
  ];
  $extra['node']['petition']['display']['nys_senator_dashboard_status'] = $nys_senator_dashboard_status;
  $extra['node']['webform']['display']['nys_senator_dashboard_status'] = $nys_senator_dashboard_status;

  $extra['node']['webform']['display']['nys_senator_dashboard_constituents_response_count'] = [
    'label' => t('NYS Senator Dashboard: Questionnaire constituents response count'),
    'description' => t('Displays the constituents response count as link to the constituents list.'),
    'weight' => 15,
    'visible' => FALSE,
  ];

  $extra['node']['webform']['display']['nys_senator_dashboard_webform_submissions_download'] = [
    'label' => t('NYS Senator Dashboard: Link to webform submissions download form'),
    'description' => t('Displays a link to the webform submissions download form.'),
    'weight' => 16,
    'visible' => FALSE,
  ];

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function nys_senator_dashboard_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  /** @var Drupal\flag\FlagService $flag_service */
  $flag_service = \Drupal::service('flag');

  $flags = $flag_service->getAllFlags($entity->getEntityTypeId(), $entity->bundle());
  foreach ($flags as $flag) {
    if (!$flag->status()) {
      continue;
    }

    if ($display->getComponent('nys_senator_dashboard_flag_link_' . $flag->id())) {
      $flag->setFlagLongText($entity->label());
      $flag->setUnflagLongText($entity->label());
      $link_type_plugin = $flag->getLinkTypePlugin();
      $flag_action_url = $link_type_plugin->getAsLink($flag, $entity, 'default')->getUrl();

      $is_flagged = $flag_service->getFlagging($flag, $entity);
      $action_class = $is_flagged ? 'action-unflag' : 'action-flag';
      $classes = [
        'flag-link',
        'flag-link-' . $flag->id(),
        $action_class,
      ];

      $build['nys_senator_dashboard_flag_link_' . $flag->id()] = [
        '#type' => 'link',
        '#title' => $entity->label(),
        '#url' => $flag_action_url,
        '#attributes' => [
          'class' => $classes,
        ],
      ];
    }

    if ($display->getComponent('nys_senator_dashboard_flag_count_' . $flag->id())) {
      $flagging_count = _nys_senator_dashboard_get_flagging_count(
        $flag->id(),
        $entity->getEntityTypeId(),
        $entity->id()
      );
      $value = match($entity->bundle()) {
        'issues' => t('@count followers', ['@count' => $flagging_count]),
        'petition' => t('Signed by @count constituents', ['@count' => $flagging_count]),
        default => $flagging_count,
      };
      $build['nys_senator_dashboard_flag_count_' . $flag->id()] = [
        '#type' => 'html_tag',
        '#tag' => 'p',
        '#value' => $value,
        '#attributes' => [
          'class' => ['flagging-count'],
        ],
      ];
    }

    if ($display->getComponent('nys_senator_dashboard_district_flag_count_' . $flag->id())) {
      $flagging_count = _nys_senator_dashboard_get_flagging_count(
        $flag->id(),
        $entity->getEntityTypeId(),
        $entity->id()
      );
      $in_district_flagging_count = _nys_senator_dashboard_get_in_district_flagging_count(
        $flag->id(),
        $entity->getEntityTypeId()
      );
      $out_district_flagging_count = $flagging_count - $in_district_flagging_count;
      $in_count = t('@in_count in-district', ['@in_count' => $in_district_flagging_count]);
      $out_count = t('@out_count out-of-district', ['@out_count' => $out_district_flagging_count]);
      $build['nys_senator_dashboard_district_flag_count_' . $flag->id()] = [
        '#markup' => "<p class='district-flagging-count'><span>$in_count</span> <span>$out_count</span></p>",
      ];
    }
  }

  if ($display->getComponent('nys_senator_dashboard_link_to_constituents_list')) {
    $url = "/senator-dashboard/constituent-activity/petitions/{$entity->id()}";
    $build['nys_senator_dashboard_link_to_constituents_list'] = [
      '#type' => 'html_tag',
      '#tag' => 'a',
      '#value' => t('View in-district signatories'),
      '#attributes' => [
        'href' => $url,
        'class' => ['link-to-constituents-list'],
      ],
    ];
  }

  if ($display->getComponent('nys_senator_dashboard_status')) {
    $value = $entity->isPublished() ? t('Active') : t('Inactive');
    $class = $entity->isPublished() ? 'active' : 'inactive';
    $build['nys_senator_dashboard_status'] = [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => $value,
      '#attributes' => [
        'class' => ["$class"],
      ],
    ];
  }

  if ($display->getComponent('nys_senator_dashboard_constituents_response_count')) {
    $url = "/senator-dashboard/constituent-activity/questionnaires/{$entity->id()}";
    $constituent_response_count = _nys_senator_dashboard_get_in_district_webform_submission_count($entity);
    $build['nys_senator_dashboard_constituents_response_count'] = [
      '#type' => 'html_tag',
      '#tag' => 'a',
      '#value' => t(
        '@constituent_response_count constituent(s) responded',
        ['@constituent_response_count' => $constituent_response_count]
      ),
      '#attributes' => [
        'href' => $url,
        'class' => ['c-senator-dashboard-questionnaire-teaser--link-to-constituents-list'],
      ]
    ];
  }

  if ($display->getComponent('nys_senator_dashboard_webform_submissions_download')) {
    $webform_id = $entity->webform?->entity?->id();
    if ($webform_id) {
      $build['nys_senator_dashboard_webform_submissions_download'] = [
        '#type' => 'html_tag',
        '#tag' => 'a',
        '#value' => t('Download all responses (CSV)'),
        '#attributes' => [
          'href' => "/admin/webform/manage/$webform_id/results/download",
          'class' => ['c-senator-dashboard-questionnaire-teaser--webform-submissions-download'],
        ]
      ];
    }
  }
}

/**
 * Counts the number of flaggings for a given entity and flag type.
 *
 * @param string $flag_id
 *   The ID of the flag type.
 * @param string $entity_type
 *   The entity type (e.g., 'node', 'user', etc.).
 * @param int $entity_id
 *   The ID of the entity being flagged.
 *
 * @return int
 *   The number of flaggings for the given entity and flag type.
 */
function _nys_senator_dashboard_get_flagging_count($flag_id, $entity_type, $entity_id) {
  $query = \Drupal::database()
    ->select('flag_counts', 'fc')
    ->fields('fc', ['count'])
    ->condition('fc.flag_id', $flag_id)
    ->condition('fc.entity_type', $entity_type)
    ->condition('fc.entity_id', $entity_id)
    ->range(0, 1);
  try {
    $result = $query->execute()->fetchField();
  }
  catch (\Exception) {
    return 0;
  }
  return (int) ($result ?: 0);
}

/**
 * Counts the number of in-district flaggings for a given entity and flag type.
 *
 * @param string $flag_id
 *   The ID of the flag type.
 * @param int $entity_id
 *   The ID of the entity being flagged.
 *
 * @return int
 *   The number of in-district flaggings for the given flag and entity IDs.
 */
function _nys_senator_dashboard_get_in_district_flagging_count($flag_id, $entity_id) {
  $active_senator_district_id = \Drupal::service('nys_senator_dashboard.managed_senators_handler')
    ->getActiveSenatorDistrictId();
  if (!$active_senator_district_id) {
    return 0;
  }

  $query = \Drupal::database()->select('flagging', 'f');
  $query->innerJoin(
    'user__field_district',
    'ufd',
    'f.uid = ufd.entity_id'
  );
  $query->condition('f.flag_id', $flag_id)
    ->condition('f.entity_id', $entity_id)
    ->condition('ufd.field_district_target_id', $active_senator_district_id);
  $count = $query->countQuery()->execute()->fetchField();

  return (int) ($count ?: 0);
}

/**
 * Gets the count of in-district constituents who submitted to the webform.
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node entity, expected to be of type "webform".
 *
 * @return int
 *   The count of in-district constituents who submitted to the webform.
 */
function _nys_senator_dashboard_get_in_district_webform_submission_count(NodeInterface $node) {
  $active_senator_district_id = \Drupal::service('nys_senator_dashboard.managed_senators_handler')
    ->getActiveSenatorDistrictId();
  $webform_id = $node->webform?->target_id;
  if (!$webform_id || !$active_senator_district_id) {
    return 0;
  }

  $query = \Drupal::database()
    ->select('webform_submission', 'ws');
  $query->join('user__field_district', 'ufd', 'ws.uid = ufd.entity_id');
  $query->condition('ws.webform_id', $webform_id);
  $query->condition('ufd.field_district_target_id', $active_senator_district_id);
  $count = $query->countQuery()->execute()->fetchField();

  return (int) $count;
}
