<?php

/**
 * @file
 * Contains custom module logic for NYS Senator Dashboard.
 */

use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_query_TAG_alter().
 *
 * Ensures views with the "senators_constituents_only" tag only display profiles
 * linked to one of the current user's managed senator's districts.
 */
function nys_senator_dashboard_query_senators_constituents_only_alter(AlterableInterface $query) {
  // Get the current user.
  try {
    $current_user = \Drupal::entityTypeManager()
      ->getStorage('user')
      ->load(\Drupal::currentUser()->id());
  }
  catch (\Throwable) {
    $query->alwaysFalse();
    return;
  }
  if (!$current_user || !$current_user->hasField('field_senator_multiref')) {
    $query->alwaysFalse();
    return;
  }

  // Get the current user's managed senators district IDs.
  $managed_senator_terms = $current_user->field_senator_multiref->referencedEntities();
  if (empty($managed_senator_terms)) {
    $query->alwaysFalse();
    return;
  }
  $managed_district_ids = [];
  foreach ($managed_senator_terms as $senator_term) {
    try {
      $senator_districts = \Drupal::entityTypeManager()
        ->getStorage('taxonomy_term')
        ->loadByProperties(['field_senator' => $senator_term->id()]);
    }
    catch (\Throwable) {
      continue;
    }
    foreach ($senator_districts as $senator_district) {
      $managed_district_ids[] = $senator_district->id();
    }
  }
  if (empty($managed_district_ids)) {
    $query->alwaysFalse();
    return;
  }

  // Get the views table alias corresponding to the users_field_data table
  // (could be users_field_data_1, etc.).
  $table_aliases = $query->getTables();
  $user_table_alias = null;
  foreach ($table_aliases as $alias => $table_info) {
    if ($table_info['table'] === 'users_field_data') {
      $user_table_alias = $alias;
      break;
    }
  }
  if (!$user_table_alias) {
    $query->alwaysFalse();
    return;
  }

  // Ensure the users being fetched are within one of the user's managed
  // senator's districts.
  $query->leftJoin(
    'user__field_district',
    'ufd',
    "{$user_table_alias}.uid = ufd.entity_id"
  );
  $query->condition('ufd.field_district_target_id', $managed_district_ids, 'IN');
}

/**
 * Implements hook_theme().
 */
function nys_senator_dashboard_theme() {
  return [
    'menu__senator_dashboard__set_active_senator' => [
      'variables' => [
        'mode' => '',
        'active_senator_links' => [],
      ],
    ],
    'menu__senator_dashboard' => [
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}
