<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('field_config_instance')
->fields(array(
  'id',
  'field_id',
  'field_name',
  'entity_type',
  'bundle',
  'data',
  'deleted',
))
->values(array(
  'id' => '83863',
  'field_id' => '7',
  'field_name' => 'field_media',
  'entity_type' => 'node',
  'bundle' => 'oembed_content',
  'data' => 'a:6:{s:5:"label";s:5:"media";s:6:"widget";a:5:{s:6:"weight";s:2:"-3";s:4:"type";s:13:"media_generic";s:6:"module";s:5:"media";s:6:"active";i:1;s:8:"settings";a:3:{s:15:"browser_plugins";a:4:{s:14:"media_internet";s:14:"media_internet";s:6:"upload";i:0;s:30:"media_default--media_browser_1";i:0;s:37:"media_default--media_browser_my_files";i:0;}s:13:"allowed_types";a:4:{s:5:"video";s:5:"video";s:5:"image";i:0;s:5:"audio";i:0;s:8:"document";i:0;}s:15:"allowed_schemes";a:4:{s:6:"oembed";s:6:"oembed";s:6:"public";s:6:"public";s:5:"vimeo";i:0;s:7:"youtube";i:0;}}}s:8:"settings";a:5:{s:14:"file_directory";s:31:"[date:custom:Y]-[date:custom:m]";s:15:"file_extensions";s:3:"txt";s:12:"max_filesize";s:0:"";s:17:"description_field";i:0;s:18:"user_register_form";b:0;}s:7:"display";a:1:{s:7:"default";a:5:{s:5:"label";s:5:"above";s:4:"type";s:12:"file_default";s:8:"settings";a:0:{}s:6:"module";s:4:"file";s:6:"weight";i:1;}}s:8:"required";i:0;s:11:"description";s:0:"";}',
  'deleted' => '0',
))
->execute();
