<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('node')
  ->fields([
    'nid' => '83863',
    'vid' => '83863',
    'type' => 'oembed_content',
    'language' => 'und',
    'title' => 'Oembed example #1',
    'uid' => '1',
    'status' => '1',
    'created' => '1648447404',
    'changed' => '1648449960',
    'comment' => '2',
    'promote' => '1',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
  ])
  ->execute();
