<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('node_revision')
  ->fields([
    'nid' => '83863',
    'vid' => '83863',
    'uid' => '1',
    'title' => 'Oembed example #1',
    'log' => '',
    'timestamp' => '1648449960',
    'status' => '1',
    'comment' => '2',
    'promote' => '1',
    'sticky' => '0',
  ])
  ->execute();
