<?php

/**
 * @file
 * Contains chart_block_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function charts_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the charts_blocks module.
    case 'help.page.charts_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create Charts blocks without the need for Views.') . '</p>';
      return $output;

    default:
  }
}
