<?php

/**
 * @file
 * Install, uninstall and update hooks for taxonomy_access_fix module.
 */

/**
 * Empty update hook to fix issue 3226641.
 */
function taxonomy_access_fix_update_8201() {
  // @see https://www.drupal.org/project/taxonomy_access_fix/issues/3226641
}

/**
 * Empty update hook to fix issue 3226641.
 */
function taxonomy_access_fix_update_8202() {
  // @see https://www.drupal.org/project/taxonomy_access_fix/issues/3226641
}
