<?php

/**
 * @file
 * Install, update and uninstall functions for the flood_control module.
 */

/**
 * Assign newly added permissions to the appropriate roles.
 */
function flood_control_update_9201() {
  $roles = user_role_names(FALSE, 'access flood unblock');
  foreach ($roles as $roleKey => $roleName) {
    user_role_grant_permissions($roleKey, [
      'administer flood unblock',
      'flood unblock ips',
    ]);
  }

}
