# Schema for configuration files of the Password Policy Blacklist submodule.

password_policy.constraint.plugin.password_blacklist:
  type: password_policy.constraint.plugin
  mapping:
    blacklist:
      type: sequence
      label: 'Blacklist'
      sequence:
        type: string
        label: 'Password'
    match_substrings:
      type: boolean
      label: 'Match substrings'
