include:
  - project: 'drupalspoons/composer-plugin'
    # Best practice is to pin to a tag or a SHA1. https://docs.gitlab.com/ee/ci/yaml/#includefile
    ref: "2.1.0"
    # The template below may be inspected at https://gitlab.com/drupalspoons/composer-plugin/-/blob/master/templates/.gitlab-ci.yml
    file: 'templates/.gitlab-ci.yml'
# Run tests on Drupal 9.1 by default, including a phpspec/prophecy-phpunit requirement.
composer_node:
  variables:
    # https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators
    DRUPAL_CORE_CONSTRAINT: ~9.1.0
  after_script:
    # See https://www.drupal.org/project/drupal/issues/3182653
    # This will fail on PHPUnit 8-, that is OK as its not needed there.
    - vendor/bin/spoon require --no-progress phpspec/prophecy-phpunit:^2 || true

phpcs:
  allow_failure: false
