<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.10 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

include 'drupal7_media' . DIRECTORY_SEPARATOR . 'actions.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'authmap.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'batch.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'block.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'block_custom.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'block_node_type.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'block_role.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'blocked_ips.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_block.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_bootstrap.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_field.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_filter.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_form.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_image.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_menu.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_page.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_path.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_views.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'cache_views_data.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'comment.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'ctools_css_cache.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'ctools_object_cache.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'date_format_locale.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'date_format_type.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'date_formats.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_config.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_config_instance.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_data_body.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_data_comment_body.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_data_field_file_image_alt_text.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_data_field_file_image_title_text.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_data_field_image.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_data_field_media.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_data_field_media_integer.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_revision_body.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_revision_comment_body.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_revision_field_file_image_alt_text.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_revision_field_file_image_title_text.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_revision_field_image.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_revision_field_media.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'field_revision_field_media_integer.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'file_display.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'file_managed.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'file_metadata.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'file_type.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'file_usage.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'filter.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'filter_format.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'flood.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'history.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'image_effects.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'image_styles.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'media_restrict_wysiwyg.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'media_view_mode_wysiwyg.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'menu_custom.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'menu_links.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'menu_router.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'node.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'node_access.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'node_comment_statistics.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'node_revision.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'node_type.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'queue.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'rdf_mapping.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'registry.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'registry_file.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'role.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'role_permission.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'search_dataset.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'search_index.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'search_node_links.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'search_total.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'semaphore.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'sequences.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'sessions.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'shortcut_set.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'shortcut_set_users.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'system.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'taxonomy_index.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'taxonomy_term_data.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'taxonomy_term_hierarchy.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'taxonomy_vocabulary.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'url_alias.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'users.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'users_roles.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'variable.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'views_display.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'views_view.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'watchdog.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'wysiwyg.php';
include 'drupal7_media' . DIRECTORY_SEPARATOR . 'wysiwyg_user.php';