<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.10 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'actions.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'authmap.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'batch.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'block.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'block_custom.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'block_node_type.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'block_role.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'blocked_ips.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_block.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_bootstrap.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_field.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_filter.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_form.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_image.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_menu.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_page.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'cache_path.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'ctools_css_cache.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'ctools_object_cache.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'date_format_locale.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'date_format_type.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'date_formats.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_config.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_config_instance.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_data_body.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_data_field_file.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_data_field_file_multi.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_data_field_image.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_data_field_image_multi.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_revision_body.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_revision_field_file.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_revision_field_file_multi.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_revision_field_image.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'field_revision_field_image_multi.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'file_managed.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'file_usage.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'filter.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'filter_format.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'flood.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'history.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'image_effects.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'image_styles.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'linkit_profiles.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'menu_custom.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'menu_links.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'menu_router.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'node.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'node_access.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'node_revision.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'node_type.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'queue.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'registry.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'registry_file.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'role.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'role_permission.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'semaphore.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'sequences.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'sessions.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'system.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'url_alias.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'users.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'users_roles.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'variable.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'wysiwyg.php';
include 'drupal7_nomedia' . DIRECTORY_SEPARATOR . 'wysiwyg_user.php';