<?php

/**
 * Tests function deprecation detection from Drupal 9 to 10.
 *
 * @deprecated in drupal:9.1.0 and is removed from drupal:10.0.0. Use the
 *   replacement instead.
 */
function upgrade_status_test_contrib_error_function_9_to_10() {
  @trigger_error("upgrade_status_test_contrib_error_function_9_to_10() is deprecated in Drupal 9.1.0 and will be removed before Drupal 10.0.0. Use the replacement instead. See LINK", E_USER_DEPRECATED);
}

/**
 * Tests function deprecation detection from Drupal 9 to 11.
 *
 * @deprecated in drupal:9.1.0 and is removed from drupal:11.0.0. Use the
 *   replacement instead.
 */
function upgrade_status_test_contrib_error_function_9_to_11() {
  @trigger_error("upgrade_status_test_contrib_error_function_9_to_11() is deprecated in Drupal 9.1.0 and will be removed before Drupal 11.0.0. Use the replacement instead. See LINK", E_USER_DEPRECATED);
}

/**
 * Tests function deprecation detection from Drupal 10 to 11.
 *
 * @deprecated in drupal:10.1.0 and is removed from drupal:11.0.0. Use the
 *   replacement instead.
 */
function upgrade_status_test_contrib_error_function_10_to_11() {
  @trigger_error("upgrade_status_test_contrib_error_function_10_to_11() is deprecated in Drupal 10.1.0 and will be removed before Drupal 11.0.0. Use the replacement instead. See LINK", E_USER_DEPRECATED);
}

/**
 * Tests function deprecation detection from Drupal 10 to 12.
 *
 * @deprecated in drupal:10.0.0 and is removed from drupal:12.0.0. Use the
 *   replacement instead.
 */
function upgrade_status_test_contrib_error_function_10_to_12() {
  @trigger_error("upgrade_status_test_contrib_error_function_10_to_12() is deprecated in Drupal 10.0.0 and will be removed before Drupal 12.0.0. Use the replacement instead. See LINK", E_USER_DEPRECATED);
}
