name: 'Charts API Example'
type: module
description: 'Demonstrates how to use the Charts module without Views.'
core: 8.x
core_version_requirement: ^8 || ^9
package: Examples
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2021-11-09
version: '8.x-3.3'
project: 'charts'
datestamp: 1636438367
