geolocation_google_maps.settings:
  type: config_object
  label: 'Geolocation settings'
  mapping:
    google_map_api_key:
      type: string
      label: 'Google Maps API Key'
    google_map_api_server_key:
      type: string
      label: 'Google Maps API Key'
    use_current_language:
      type: boolean
      label: 'Use current language'
    china_mode:
      type: boolean
      label: 'China mode'
    google_maps_base_url:
      type: string
      label: 'Google Maps Base URL Override'
    google_map_custom_url_parameters:
      type: mapping
      label: 'Additional Google Maps API parameters'
      mapping:
        region:
          type: string
          label: 'Region'
        language:
          type: string
          label: 'languae'
        v:
          type: string
          label: 'Version'
        client:
          type: string
          label: 'Client ID'
        channel:
          type: string
          label: 'Channel ID'
        libraries:
          type: sequence
          label: 'Libraries'
          sequence:
            type: string
            label: 'Library name'

geolocation.geocoder.google_geocoding_api:
  type: geolocation_geocoder
  label: 'Google Geocoding API'
  mapping:
    autocomplete_min_length:
      type: integer
      label: 'Autocomplete MinLength'
    component_restrictions:
      type: mapping
      label: 'Components'
      mapping:
        route:
          type: string
          label: 'Route'
        country:
          type: string
          label: 'Country'
        administrative_area:
          type: string
          label: 'Administrative Area'
        locality:
          type: string
          label: 'Locality'
        postal_code:
          type: string
          label: 'Postal Code'
    boundary_restriction:
      type: mapping
      label: 'Boundaries'
      mapping:
        south:
          type: string
          label: 'South'
        west:
          type: string
          label: 'West'
        north:
          type: string
          label: 'North'
        east:
          type: string
          label: 'East'
    region:
      type: string
      label: 'Region ccTLD'

geolocation.map_provider.google_maps:
  type: geolocation_map_provider
  label: 'Google Map settings'
  mapping:
    type:
      type: string
      label: 'Google map type'
    zoom:
      type: integer
      label: 'Zoom level'
    minZoom:
      type: integer
      label: 'Min Zoom'
    maxZoom:
      type: integer
      label: 'Max Zoom'
    rotateControl:
      type: boolean
      label: 'The state of the rotate control'
    height:
      type: string
      label: 'Height value'
    width:
      type: string
      label: 'Width value'
    gestureHandling:
      type: string
      label: 'Smart scrolling'
