geolocation.leaflet.tile_layer_provider:
  type: config_object
  label: 'Leaflet Tile Layer Provider'
  sequence:
    type: geolocation.leaflet.tile_layer
    label: 'Tile layer'

geolocation.leaflet.tile_layer:
  type: config_object
  label: 'Leaflet Tile Layer'
  mapping:
    checkbox:
      type: boolean
      label: 'Enabled'

# OpenStreetMap
geolocation.map_feature_settings.leaflet.tile_layer_provider.OpenStreetMap:
  type: geolocation.leaflet.tile_layer_provider
  label: 'OpenStreetMap'


#OpenTopoMap
geolocation.map_feature_settings.leaflet.tile_layer_provider.OpenTopoMap:
  type: geolocation.leaflet.tile_layer_provider
  label: 'OpenTopoMap'

#Thunderforest
geolocation.map_feature_settings.leaflet.tile_layer_provider.Thunderforest:
  type: geolocation.leaflet.tile_layer_provider
  label: 'Thunderforest'
  mapping:
    apikey:
      type: string
      label: 'API key'

#OpenMapSurfer
geolocation.map_feature_settings.leaflet.tile_layer_provider.OpenMapSurfer:
  type: geolocation.leaflet.tile_layer_provider
  label: 'OpenMapSurfer'

#Hydda
geolocation.map_feature_settings.leaflet.tile_layer_provider.Hydda:
  type: geolocation.leaflet.tile_layer_provider
  label: 'Hydda'

#MapBox
geolocation.map_feature_settings.leaflet.tile_layer_provider.MapBox:
  type: geolocation.leaflet.tile_layer_provider
  label: 'MapBox'
  mapping:
    accessToken:
      type: string
      label: 'Access Token'

#MtbMap
geolocation.map_feature_settings.leaflet.tile_layer_provider.MtbMap:
  type: geolocation.leaflet.tile_layer_provider
  label: 'MtbMap'

#FreeMapSK
geolocation.map_feature_settings.leaflet.tile_layer_provider.FreeMapSK:
  type: geolocation.leaflet.tile_layer_provider
  label: 'FreeMapSK'

#NLS
geolocation.map_feature_settings.leaflet.tile_layer_provider.NLS:
  type: geolocation.leaflet.tile_layer_provider
  label: 'NLS'

#HERE
geolocation.map_feature_settings.leaflet.tile_layer_provider.HERE:
  type: geolocation.leaflet.tile_layer
  label: 'HERE'
  mapping:
    app_id:
      type: string
      label: 'app ID'
    app_code:
      type: string
      label: 'app code'

#GeoportailFrance
geolocation.map_feature_settings.leaflet.tile_layer_provider.GeoportailFrance:
  type: geolocation.leaflet.tile_layer
  label: 'GeoportailFrance'
  mapping:
    apikey:
      type: string
      label: 'API key'

#Stamen
geolocation.map_feature_settings.leaflet.tile_layer_provider.Stamen:
  type: geolocation.leaflet.tile_layer
  label: 'Stamen'

#HikeBike
geolocation.map_feature_settings.leaflet.tile_layer_provider.HikeBike:
  type: geolocation.leaflet.tile_layer
  label: 'HikeBike'

#Esri
geolocation.map_feature_settings.leaflet.tile_layer_provider.Esri:
  type: geolocation.leaflet.tile_layer
  label: 'Esri'

#BasemapAT
geolocation.map_feature_settings.leaflet.tile_layer_provider.BasemapAT:
  type: geolocation.leaflet.tile_layer
  label: 'BasemapAT'

#CartoDB
geolocation.map_feature_settings.leaflet.tile_layer_provider.CartoDB:
  type: geolocation.leaflet.tile_layer
  label: 'CartoDB'
