plugin.plugin_configuration.geolocation.map_feature.leaflet_marker_popup:
  type: geolocation.map_feature_settings
  label: 'Marker Popup'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        info_auto_display:
          type: boolean
          label: 'Show info window on map start'
        max_width:
          type: integer
          label: 'Popup max width'
        min_width:
          type: integer
          label: 'Popup min width'
        max_height:
          type: integer
          label: 'Popup max height'
        auto_pan:
          type: boolean
          label: 'Popup auto pan'
        keep_in_view:
          type: boolean
          label: 'Popup keep in view'
        close_button:
          type: boolean
          label: 'Popup close button'
        auto_close:
          type: boolean
          label: 'Popup auto close'
        close_on_escape_key:
          type: boolean
          label: 'Popup close with escape'
        class_name:
          type: string
          label: 'Popup class name'


plugin.plugin_configuration.geolocation.map_feature.leaflet_marker_clusterer:
  type: geolocation.map_feature_settings
  label: 'Marker Clusterer'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        cluster_settings:
          type: mapping
          label: 'Cluster Settings'
          mapping:
            show_coverage_on_hover:
              type: boolean
              label: 'Setting'
            zoom_to_bounds_on_click:
              type: boolean
              label: 'Setting'
        disable_clustering_at_zoom:
          type: integer
          label: 'Max Zoom for clustering'
        custom_marker_settings:
          type: string
          label: 'Custom Marker Settings'

geolocation.map_feature_settings.leaflet.control:
  type: geolocation.map_feature_settings
  label: 'Control Element'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        position:
          type: string
          label: 'Position'

plugin.plugin_configuration.geolocation.map_feature.leaflet_control_zoom:
  type: geolocation.map_feature_settings.leaflet.control
  label: 'Control Zoom'

plugin.plugin_configuration.geolocation.map_feature.leaflet_control_fullscreen:
  type: geolocation.map_feature_settings.leaflet.control
  label: 'Control Fullscreen'

plugin.plugin_configuration.geolocation.map_feature.leaflet_control_geocoder:
  type: geolocation.map_feature_settings.leaflet.control
  label: 'Control Geocoder'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        geocoder:
          type: string
          label: 'Geocoder'
        settings:
          type: geolocation.geocoder.[%parent.geocoder]

plugin.plugin_configuration.geolocation.map_feature.leaflet_control_locate:
  type: geolocation.map_feature_settings.leaflet.control
  label: 'Control Locate'

plugin.plugin_configuration.geolocation.map_feature.leaflet_control_recenter:
  type: geolocation.map_feature_settings.leaflet.control
  label: 'Control Recenter'

plugin.plugin_configuration.geolocation.map_feature.leaflet_control_attribution:
  type: geolocation.map_feature_settings.leaflet.control
  label: 'Control Attribution'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        prefix:
          type: string
          label: 'Prefix'

plugin.plugin_configuration.geolocation.map_feature.leaflet_control_scale:
  type: geolocation.map_feature_settings.leaflet.control
  label: 'Control Scale'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        metric:
          type: boolean
          label: 'Metric'
        imperial:
          type: boolean
          label: 'Imperial'

plugin.plugin_configuration.geolocation.map_feature.leaflet_control_layer:
  type: geolocation.map_feature_settings.leaflet.control
  label: 'Control Layer'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        default_label:
          type: string
          label: 'Label'
        tile_layer_providers:
          type: sequence
          label: 'Providers'
          sequence:
            type: sequence
            label: 'MapType'
            sequence:
              type: mapping
              label: 'Enabled'
              mapping:
                checkbox:
                  type: boolean
                  label: 'Enabled'
                label:
                  type: string
                  label: 'Label'
        tile_providers_options:
          type: sequence
          label: 'Providers'
          sequence:
            type: geolocation.map_feature_settings.leaflet.tile_layer_provider.[%key]
            label: 'Provider Options'

plugin.plugin_configuration.geolocation.map_feature.leaflet_marker_icon:
  type: geolocation.map_feature_settings
  label: 'Marker Icon'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        marker_shadow_path:
          type: string
          label: 'Shadow Path'
        marker_icon_path:
          type: string
          label: 'Icon path'
        icon_size:
          type: mapping
          label: 'Icon Size'
          mapping:
            width:
              type: integer
              label: 'Width'
            height:
              type: integer
              label: 'Height'
        icon_anchor:
          type: mapping
          label: 'Icon Anchor'
          mapping:
            x:
              type: integer
              label: 'Width'
            y:
              type: integer
              label: 'Height'
        popup_anchor:
          type: mapping
          label: 'Popup Anchor'
          mapping:
            x:
              type: integer
              label: 'Width'
            y:
              type: integer
              label: 'Height'
        shadow_size:
          type: mapping
          label: 'Shadow Size'
          mapping:
            width:
              type: integer
              label: 'Width'
            height:
              type: integer
              label: 'Height'
        shadow_anchor:
          type: mapping
          label: 'Shadow Anchor'
          mapping:
            x:
              type: integer
              label: 'Width'
            y:
              type: integer
              label: 'Height'

plugin.plugin_configuration.geolocation.map_feature.leaflet_marker_zoom_and_animate:
  type: geolocation.map_feature_settings
  label: 'Marker zoom and animate'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        marker_zoom_anchor_id:
          type: string
          label: 'Anchor ID'

plugin.plugin_configuration.geolocation.map_feature.leaflet_max_bounds:
  type: geolocation.map_feature_settings
  label: 'Max Bounds'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        north:
          type: float
          label: 'North'
        south:
          type: float
          label: 'South'
        east:
          type: float
          label: 'East'
        west:
          type: float
          label: 'West'

plugin.plugin_configuration.geolocation.map_feature.leaflet_custom_tile_layer:
  type: geolocation.map_feature_settings
  label: 'Custom Tile Layer'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        tile_layer_url:
          type: string
          label: 'Url'
        tile_layer_attribution:
          type: string
          label: 'Attribution'
        tile_layer_subdomains:
          type: string
          label: 'Subdomains'
        tile_layer_zoom:
          type: integer
          label: 'Zoom'

plugin.plugin_configuration.geolocation.map_feature.leaflet_tile_layer:
  type: geolocation.map_feature_settings
  label: 'Tile Layer'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        tile_layer_provider:
          type: string
          label: 'Overlay'
        tile_provider_options:
          type: sequence
          label: 'Provider Options'
          sequence:
            type: geolocation.map_feature_settings.leaflet.tile_layer_provider.[%key]
            label: 'Provider Options'

plugin.plugin_configuration.geolocation.map_feature.leaflet_tile_layer_overlay:
  type: geolocation.map_feature_settings
  label: 'Tile Layer Overlay'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        tile_layer_overlay:
          type: string
          label: 'Overlay'
        tile_overlay_options:
          type: mapping
          label: 'Options'
          mapping:
            apiKey:
              type: string
              label: 'API key'

plugin.plugin_configuration.geolocation.map_feature.leaflet_wms:
  type: geolocation.map_feature_settings
  label: 'Leaflet WMS'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        url:
          type: string
          label: 'Url'
        version:
          type: string
          label: 'Version'
        layers:
          type: string
          label: 'Layers'
        styles:
          type: string
          label: 'Styles'
        srs:
          type: string
          label: 'SRS'
        format:
          type: string
          label: 'Format'
        transparent:
          type: boolean
          label: 'Transparent'
        identify:
          type: boolean
          label: 'Identify'
plugin.plugin_configuration.geolocation.map_feature.leaflet_rotate:
  type: geolocation.map_feature_settings
  label: 'Leaflet Rotate'
  mapping:
    settings:
      type: mapping
      label: 'Rotation Settings'
      mapping:
        display_control:
          type: boolean
          label: 'Display Rotation Control'
        bearing:
          type: float
          label: 'Bearing'