<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('node')
->fields(array(
  'nid',
  'vid',
  'type',
  'language',
  'title',
  'uid',
  'status',
  'created',
  'changed',
  'comment',
  'promote',
  'sticky',
  'tnid',
  'translate',
))
->values(array(
  'nid' => '40',
  'vid' => '40',
  'type' => 'youtubecontent',
  'language' => 'und',
  'title' => 'YouTube example #1',
  'uid' => '1',
  'status' => '1',
  'created' => '1648447404',
  'changed' => '1648449960',
  'comment' => '2',
  'promote' => '1',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
))
->values(array(
  'nid' => '50',
  'vid' => '50',
  'type' => 'youtubecontent',
  'language' => 'und',
  'title' => 'YouTube example #2',
  'uid' => '1',
  'status' => '1',
  'created' => '1648450023',
  'changed' => '1648561267',
  'comment' => '2',
  'promote' => '1',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
))
->execute();
