<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('system')
->fields(array(
  'filename' => 'sites/all/modules/contrib/youtube/youtube.module',
  'name' => 'youtube',
  'type' => 'module',
  'owner' => '',
  'status' => '1',
  'bootstrap' => '0',
  'schema_version' => '7103',
  'weight' => '0',
  'info' => 'a:16:{s:4:"name";s:13:"YouTube Field";s:11:"description";s:37:"Provides a YouTube widget for fields.";s:7:"package";s:6:"Fields";s:4:"core";s:3:"7.x";s:12:"dependencies";a:3:{i:0;s:5:"field";i:1;s:5:"image";i:2;s:4:"file";}s:5:"files";a:1:{i:0;s:19:"youtube.migrate.inc";}s:11:"stylesheets";a:1:{s:3:"all";a:1:{s:15:"css/youtube.css";s:49:"sites/all/modules/contrib/youtube/css/youtube.css";}}s:9:"configure";s:26:"admin/config/media/youtube";s:7:"version";s:7:"7.x-1.8";s:7:"project";s:7:"youtube";s:9:"datestamp";s:10:"1573591329";s:5:"mtime";i:1573591329;s:3:"php";s:5:"5.2.4";s:9:"bootstrap";i:0;s:8:"required";b:1;s:11:"explanation";s:73:"Field type(s) in use - see <a href="/admin/reports/fields">Field list</a>";}',
))
->execute();
