<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('variable', array(
  'fields' => array(
    'name' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'value' => array(
      'type' => 'blob',
      'not null' => TRUE,
      'size' => 'big',
    ),
  ),
  'primary key' => array(
    'name',
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('variable')
->fields(array(
  'name',
  'value',
))
->values(array(
  'name' => 'fontawesome_allow_pseudo_elements',
  'value' => 'i:1;',
))
->values(array(
  'name' => 'fontawesome_external',
  'value' => 'a:2:{s:7:"use_cdn";i:1;s:17:"external_location";s:54:"https://use.fontawesome.com/releases/v5.11.2/js/all.js";}',
))
->values(array(
  'name' => 'fontawesome_method',
  'value' => 's:3:"svg";',
))
->values(array(
  'name' => 'fontawesome_partial',
  'value' => 'a:4:{s:14:"use_solid_file";i:1;s:16:"use_regular_file";i:1;s:14:"use_light_file";i:1;s:15:"use_brands_file";i:1;}',
))
->values(array(
  'name' => 'fontawesome_shim',
  'value' => 'a:2:{s:8:"use_shim";i:1;s:17:"external_location";s:27:"docroot/library/fontawesome";}',
))
->execute();
