<?php

/**
 * @file
 * Hook implementations for the Password History module.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_user_insert().
 */
function password_policy_history_user_insert(AccountInterface $account) {
  _password_policy_history_insert_password_hash($account);
}

/**
 * Implements hook_user_update().
 */
function password_policy_history_user_update(AccountInterface $account) {
  _password_policy_history_insert_password_hash($account);
}

/**
 * Get hashed password and insert it into the history table.
 *
 * @param \Drupal\Core\Session\AccountInterface $account
 *   The current user account.
 */
function _password_policy_history_insert_password_hash(AccountInterface $account) {
  if (empty($_POST['pass']['pass1']) || empty($_POST['pass']['pass2'])) {
    return;
  }
  $connection = Database::getConnection();

  $hashed_pass = $account->getPassword();
  if (!$hashed_pass) {
    return;
  }

  $values = [
    $account->id(),
    $hashed_pass,
    \Drupal::time()->getRequestTime(),
  ];
  $connection->insert('password_policy_history')
    ->fields(['uid', 'pass_hash', 'timestamp'], $values)
    ->execute();
}

/**
 * Implements hook_user_delete().
 */
function password_policy_history_user_delete($account) {
  \Drupal::database()->delete('password_policy_history')
    ->condition('uid', $account->id())
    ->execute();
}
