charts_billboard:
  version: 1.x
  js:
    js/charts_billboard.js: { weight: -1 }
  dependencies:
    - charts/global
    - core/drupal
    - core/once
d3:
  remote: 'https://cdnjs.cloudflare.com/ajax/libs/d3/6.7.0/d3.min.js'
  version: 6.7.0
  license:
    name: BSD
    url: 'https://en.wikipedia.org/wiki/BSD_licenses'
    gpl-compatible: false
  cdn:
    /libraries/d3/: https://cdnjs.cloudflare.com/ajax/libs/d3/6.7.0/
  js:
    /libraries/d3/d3.min.js: {  }
billboard:
  remote: 'https://naver.github.io/billboard.js/release/3.7.5/dist/billboard.min.js'
  version: 3.7.5
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
    gpl-compatible: true
  cdn:
    /libraries/billboard/: https://naver.github.io/billboard.js/release/3.7.5/
  css:
    theme:
      /libraries/billboard/dist/billboard.min.css: {  }
  js:
    /libraries/billboard/dist/billboard.min.js: {  }
  dependencies:
    - charts_billboard/charts_billboard
    - charts_billboard/d3
