_core:
  default_config_hash: YA7-DHZTafx26xj7TsHR42czXDALmPcX39-Qzh9tbs4
langcode: en
subject: 'One Time Password'
body: "Dear [user:name],\r\n    \r\nYour One Time Passcode for completing your NY Senate TFA Verification is: [user:email_tfa]\r\n    \r\nPlease use this Passcode to complete your transaction. Do not share this Passcode with anyone.\r\n    \r\nThank you,\r\n[site:name] team"
routes: "email_tfa.verifiy\r\nuser.logout"
timeouts: 300
status: false
tracks: globally_enabled
user_one: false
role_exclusion_type: force_for
ignore_role:
  - administrator
  - comment_moderator
  - frontpage_editor
  - legislative_correspondent
  - microsite_content_producer
  - senator
  - student_programs
security_code_label_text: 'One-time security code'
security_code_description_text: 'We sent you an email containing your one-time security code. Please enter the code provided to proceed.'
security_code_verify_text: Verify
verification_succeeded_message: 'One-time security code verification succeeded.'
verification_failed_message: 'One-time security code verification failed.'
security_code_length: 8
dev_mode: false
security_code_resend_text: Resend
verification_not_authorized_message: 'You are not authorized to access this page.'
log_events: false
flood_threshold: 5
flood_window: 3600
