block.settings.contact_block:
  type: block_settings
  label: 'Contact block'
  mapping:
    contact_form:
      type: string
      label: 'Contact form'
    form_display:
      type: string
      label: 'Form display'
