id: d7_field_instance_widget_settings_location
label: Geolocation field instance widget configuration for Location
migration_tags:
  - Drupal 7
  - Configuration
deriver: Drupal\geolocation_address\Plugin\migrate\D7LocationFieldDeriver
source:
  plugin: d7_field_widget_settings_location
  constants:
    form_mode: default
    widget_type: geolocation_latlng
    settings: []
    third_party_settings: { }
process:
  entity_type: entity_type
  bundle: bundle
  field_name: geolocation_field_name
  form_mode: constants/form_mode
  'options/weight': widget/weight
  'options/type': constants/widget_type
  'options/settings': constants/settings
  'options/third_party_settings': constants/third_party_settings
destination:
  plugin: component_entity_form_display
migration_dependencies:
  required:
    - d7_field_instance_location
