# Schema for configuration files of the Password Policy History submodule.

password_policy.constraint.plugin.password_policy_history_constraint:
  type: password_policy.constraint.plugin
  mapping:
    history_repeats:
      type: integer
