node_revision_delete:
  label: 'Node revisions delete'
  plugin_manager_service_id: plugin.manager.node_revision_delete
  plugin_definition_decorator_class: \Drupal\plugin\PluginDefinition\ArrayPluginDefinitionDecorator
