geolocation.map_provider.here:
  type: geolocation_map_provider
  label: 'HERE Maps settings'
  mapping:
    zoom:
      type: string
      label: 'Zoom level'
    height:
      type: string
      label: 'Height value'
    width:
      type: string
      label: 'Width value'
