block.settings.geolocation_block:
  type: block_settings
  label: 'Geolocation block'
  mapping:
    centre:
      type: sequence
      label: 'Center option settings'
      sequence:
        type: plugin.plugin_configuration.geolocation.map_center_option.[%key]
        label: 'The settings for a map center option'
    map_provider_id:
      type: string
      label: 'Map provider ID'
    map_provider_settings:
      type: geolocation.map_provider.[%parent.map_provider_id]
      label: 'Map provider settings'
    locations:
      type: sequence
      label: 'Locations'
      sequence:
        type: mapping
        label: 'Default value'
        mapping:
          marker_title:
            type: string
            label: 'Marker Title'
          marker_content:
            type: text_format
            label: 'Marker Content'
          marker_coordinates:
            type: geolocation.element.input
            label: 'Coordinates'
