core.entity_form_display.*.*.*.third_party.rain_admin_field_label:
  type: mapping
  label: 'Rain admin field label field settings'
  mapping:
    hide_field_input_label:
      type: boolean
      label: 'Whether to hide the field label on the entity form.'