geolocation_yandex.settings:
  type: config_object
  label: 'Geolocation settings'
  mapping:
    api_key:
      type: string
      label: 'Yandex Maps API Key'
    packages:
      type: sequence
      label: 'Yandex Maps API Packages'
      sequence:
        type: string
        label: 'Package'

geolocation.map_provider.yandex:
  type: geolocation_map_provider
  label: 'Yandex Maps settings'
  mapping:
    zoom:
      type: string
      label: 'Zoom level'
    max_zoom:
      type: string
      label: 'Max Zoom level'
    min_zoom:
      type: string
      label: 'Min Zoom level'
    height:
      type: string
      label: 'Height value'
    width:
      type: string
      label: 'Width value'
