id: password_policy_settings
label: Password policy configuration
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: password_policy
process:
  id:
    -
      plugin: machine_name
      source: name
  password_policy_constraints:
    -
      plugin: default_value
      source: config
      default_value: "a:0:{}"
    -
      plugin: callback
      callable: unserialize
    -
      plugin: policy_configuration
  label: '@password_policy_constraints/label'
  policy_constraints: '@password_policy_constraints/constraints'
  roles: '@password_policy_constraints/roles'
  password_reset: '@password_policy_constraints/password_reset'
  send_reset_email: '@password_policy_constraints/send_reset_email'
  send_pending_email: '@password_policy_constraints/days'
destination:
  plugin: entity:password_policy
migration_dependencies:
  required:
    - d7_user_role
