<?php
/**
 * @file
 * Install, update and uninstall hooks for the Rain Resource Type feature module.
 */

use Drupal\user\Entity\Role;
use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function rain_resource_type_install() {
  // Add view terms permission.
  $role_object = Role::load('anonymous');
  $role_object->grantPermission('view terms in resource');
  $role_object->save();
}
