id: d7_captcha_settings
label: 'Captcha Settings'
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - captcha_administration_mode
    - captcha_allow_on_admin_pages
    - captcha_default_challenge
    - captcha_default_challenge_on_nonlisted_forms
    - captcha_default_validation
    - captcha_description
    - captcha_enable_stats
    - captcha_error_message
    - captcha_log_wrong_responses
    - captcha_persistence
    - captcha_placement_map_cache
  source_module: captcha
process:
  enable_globally: captcha_default_challenge_on_nonlisted_forms
  enable_globally_on_admin_routes: captcha_allow_on_admin_pages
  default_challenge: captcha_default_challenge
  description: captcha_description
  administration_mode: captcha_administration_mode
  administration_mode_on_admin_routes: captcha_allow_on_admin_pages
  default_validation: captcha_default_validation
  persistence: captcha_persistence
  enable_stats: captcha_enable_stats
  log_wrong_responses: captcha_log_wrong_responses
destination:
  plugin: config
  config_name: captcha.settings
