<?php

/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('field_config', [
  'fields' => [
    'id' => [
      'type' => 'serial',
      'not null' => TRUE,
      'size' => 'normal',
    ],
    'field_name' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '32',
    ],
    'type' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
    ],
    'module' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ],
    'active' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ],
    'storage_type' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
    ],
    'storage_module' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ],
    'storage_active' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ],
    'locked' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ],
    'data' => [
      'type' => 'blob',
      'not null' => TRUE,
      'size' => 'big',
    ],
    'cardinality' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ],
    'translatable' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ],
    'deleted' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ],
  ],
  'primary key' => [
    'id',
  ],
  'indexes' => [
    'field_name' => [
      'field_name',
    ],
    'active' => [
      'active',
    ],
    'storage_active' => [
      'storage_active',
    ],
    'deleted' => [
      'deleted',
    ],
    'module' => [
      'module',
    ],
    'storage_module' => [
      'storage_module',
    ],
    'type' => [
      'type',
    ],
    'storage_type' => [
      'storage_type',
    ],
  ],
  'mysql_character_set' => 'utf8mb3',
]);
