<?php

/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('users', [
  'fields' => [
    'uid' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ],
    'name' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '60',
      'default' => '',
    ],
    'pass' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ],
    'mail' => [
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '254',
      'default' => '',
    ],
    'theme' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ],
    'signature' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ],
    'signature_format' => [
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '255',
    ],
    'created' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ],
    'access' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ],
    'login' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ],
    'status' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ],
    'timezone' => [
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '32',
    ],
    'language' => [
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '12',
      'default' => '',
    ],
    'picture' => [
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ],
    'init' => [
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '254',
      'default' => '',
    ],
    'data' => [
      'type' => 'blob',
      'not null' => FALSE,
      'size' => 'big',
    ],
  ],
  'primary key' => [
    'uid',
  ],
  'unique keys' => [
    'name' => [
      'name',
    ],
  ],
  'indexes' => [
    'access' => [
      'access',
    ],
    'created' => [
      'created',
    ],
    'mail' => [
      'mail',
    ],
    'picture' => [
      'picture',
    ],
  ],
  'mysql_character_set' => 'utf8mb3',
]);
