name: Environment indicator UI
type: module
description: Provides a UI for environment indicator toolbar configurations.
package: Development
core_version_requirement: ^9.2 || ^10
dependencies:
  - environment_indicator:environment_indicator

configure: environment_indicator_ui.settings

# Information added by Drupal.org packaging script on 2023-10-06
version: '4.0.17'
project: 'environment_indicator'
datestamp: 1696608290
