name: Environment indicator UI
type: module
description: Provides a UI for environment indicator toolbar configurations.
package: Development
core_version_requirement: ^8.8 || ^9
dependencies:
  - environment_indicator:environment_indicator

configure: environment_indicator_ui.settings

# Information added by Drupal.org packaging script on 2022-07-23
version: '4.0.7'
project: 'environment_indicator'
datestamp: 1658608645
