name: Environment indicator UI
type: module
description: Provides a UI for environment indicator toolbar configurations.
package: Development
core_version_requirement: ^9.2 || ^10
dependencies:
  - environment_indicator:environment_indicator

configure: environment_indicator_ui.settings

# Information added by Drupal.org packaging script on 2024-05-31
version: '4.0.18'
project: 'environment_indicator'
datestamp: 1717143730
