<?php

/**
 * @file
 * Hook implementations for the Password Policy test module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function password_policy_test_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hide the password field if a test requires it. This mimicks functionality
  // offered by modules that offer optional external authentication methods,
  // such as the CAS and LDAP modules. They will hide the password field if the
  // user is authenticated externally.
  if (\Drupal::state()->get('password_policy_test.user_form.hide_password', FALSE)) {
    $form['account']['pass']['#access'] = FALSE;
    $form['account']['current_pass']['#access'] = FALSE;
  }
}
