geolocation_geocodio.settings:
  type: config_object
  label: 'Geolocation settings'
  mapping:
    api_key:
      type: string
      label: 'Geocodio API Key'
    fields:
      type: string
      label: 'Geocodio Fields'

geolocation.geocoder.geocodio:
  type: geolocation_geocoder
  label: 'Geocodio'
  mapping:
    autocomplete_min_length:
      type: integer
      label: 'Autocomplete MinLength'
    component_restrictions:
      type: mapping
      label: 'Components'
      mapping:
        route:
          type: string
          label: 'Route'
        country:
          type: string
          label: 'Country'
        administrative_area:
          type: string
          label: 'Administrative Area'
        locality:
          type: string
          label: 'Locality'
        postal_code:
          type: string
          label: 'Postal Code'
