name: Config Split
type: module
description: Configuration transformer for importing and exporting split config
core_version_requirement: ^8.8 || ^9 || ^10
package: Config
configure: entity.config_split.collection

# Information added by Drupal.org packaging script on 2023-11-06
version: '2.0.0'
project: 'config_split'
datestamp: 1699259256
