<?php

/**
 * @file
 * Implement module related hooks for the charts_google module.
 */

/**
 * Implements hook_charts_version3_to_new_settings_structure_alter().
 */
function charts_google_charts_version3_to_new_settings_structure_alter(array &$new_settings, string $for) {
  $config_factory = \Drupal::configFactory();
  $google_config = $config_factory->getEditable('charts_google.settings');
  if ($google_config) {
    $google_config->delete();
  }
}
