<?php

/**
 * @file
 * Contains custom blocks.
 */

/**
 * Implements hook_theme().
 */
function nys_blocks_theme($existing, $type, $theme, $path):array {
  return [
    'nys_blocks_senate_works' => [
      'variables' => [
        'display_name' => NULL,
      ],
    ],
    'nys_blocks_want_to' => [
      'variables' => [
        'headshot' => NULL,
        'senator_link' => NULL,
        'register' => NULL,
      ],
    ],
    'nys_blocks_bythe_numbers' => [
      'variables' => [
        'display_name' => NULL,
        'first_year' => NULL,
        'second_year' => NULL,
        'session_year' => NULL,
      ],
    ],
    'nys_blocks_about_text' => [
      'variables' => [
        'display_name' => NULL,
        'about_text' => NULL,
      ],
    ],
    'nys_blocks_calendar_downloads' => [
      'variables' => [
        'session_calendar_pdf_href' => NULL,
        'public_hearing_schedule_href' => NULL,
      ],
    ],
    'nys_blocks_contact_us' => [
      'variables' => [
        'display_name' => NULL,
      ],
    ],
  ];
}
