<?php

/**
 * @file
 * Contains custom code for Events and their Microsite Content.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_mail().
 */
function nys_messaging_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'forward_message':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['body'][] = $params['message'];
      break;
  }
}
