field.formatter.settings.geolocation_address:
  type: geolocation.field.formatter.map.base
  label: 'Geolocation Address Google Map formatter settings'
  mapping:
    data_provider_settings:
      label: 'Data provider settings'
      type: geolocation.data_provider.geolocation_address_field_provider
field.widget.third_party.geolocation_address:
  type: mapping
  label: 'Address integration settings'
  mapping:
    enable:
      type: boolean
    address_field:
      type: string
    geocoder:
      type: string
    settings:
      type: mapping
      mapping:
        label:
          type: string
        description:
          type: string
        autocomplete_min_length:
          type: integer
          label: 'Autocomplete MinLength'
        component_restrictions:
          type: mapping
          label: 'Components'
          mapping:
            route:
              type: string
              label: 'Route'
            country:
              type: string
              label: 'Country'
            administrative_area:
              type: string
              label: 'Administrative Area'
            locality:
              type: string
              label: 'Locality'
            postal_code:
              type: string
              label: 'Postal Code'
        boundary_restriction:
          type: mapping
          label: 'Boundaries'
          mapping:
            south:
              type: string
              label: 'South'
            west:
              type: string
              label: 'West'
            north:
              type: string
              label: 'North'
            east:
              type: string
              label: 'East'
        region:
          type: string
          label: 'Region ccTLD'
    sync_mode:
      type: string
    button_position:
      type: string
    direction:
      type: string
    ignore:
      type: mapping
      mapping:
        organization:
          type: boolean
        address-line1:
          type: boolean
        address-line2:
          type: boolean
        locality:
          type: boolean
        administrative-area:
          type: boolean
        postal-code:
          type: boolean
