field.formatter.settings.geolocation_address:
  type: geolocation.field.formatter.map.base
  label: 'Geolocation Address Google Map formatter settings'
  mapping:
    data_provider_settings:
      label: 'Data provider settings'
      type: geolocation.data_provider.geolocation_address_field_provider
field.widget.third_party.geolocation_address:
  type: mapping
  label: 'Address integration settings'
  mapping:
    enable:
      type: boolean
    address_field:
      type: string
    geocoder:
      type: string
    settings:
      type: geolocation.geocoder.[%parent.geocoder]
    sync_mode:
      type: string
    button_position:
      type: string
    direction:
      type: string
    ignore:
      type: mapping
      mapping:
        organization:
          type: boolean
        address-line1:
          type: boolean
        address-line2:
          type: boolean
        locality:
          type: boolean
        administrative-area:
          type: boolean
        postal-code:
          type: boolean
