include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  _PHPUNIT_CONCURRENT: 1
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 1


phpunit (next major):
  variables:
    SYMFONY_DEPRECATIONS_HELPER: "disabled"

phpcs:
  allow_failure: false

phpstan:
  allow_failure: false

phpstan (next major):
  allow_failure: true

phpstan (next minor):
  allow_failure: true
