<?php

/**
 * @file
 * Provides alterations for Drupal contrib modules.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nys_contrib_alters_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_event_form' || $form_id == 'node_session_form' || $form_id == 'node_public_hearing_form' || $form_id == 'node_school') {
    $form['field_location']['widget'][0]['#after_build'][] = 'nys_contrib_alters_customize_address';
  }
  if (($form_id === 'node_public_hearing_form') || ($form_id === 'node_session_form') || ($form_id === 'node_event_form')) {
    unset($form['field_event_place']['widget']['#options']['cap']);
    unset($form['field_event_place']['widget']['#options']['lob']);
  }
  if (($form_id === 'node_public_hearing_form') || ($form_id === 'node_meeting_form')) {
    unset($form['field_event_place']['widget']['#options']['teleconference']);
  }
  if ($form_id === 'node_meeting_form') {
    unset($form['field_event_place']['widget']['#options']['in_district']);
    unset($form['field_event_place']['widget']['#options']['in_albany']);
  }
  if ($form_id === 'node_event_form') {
    unset($form['field_video_status']['widget']['#options']['cancelled']);
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function nys_contrib_alters_field_formatter_info_alter(array &$info) {
  // Make the boolean formatter apply to all field_types.
  $info['boolean']['field_types'] = array_keys(
    \Drupal::service('plugin.manager.field.field_type')->getDefinitions()
  );
}

/**
 * Renames labels in address contrib module.
 */
function nys_contrib_alters_customize_address($element, $form_state): array {
  $element['address']['organization']['#title'] = t('Location Name');
  $element['address']['address_line1']['#title'] = t('Street');
  $element['address']['address_line2']['#title'] = t('Additional');
  $element['address']['address_line2']['#title_display'] = 'before';
  $element['address']['country_code']['#access'] = FALSE;
  return $element;
}
