<?php

/**
 * @file
 * Provides alterations for Drupal contrib modules.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */

function nys_contrib_alters_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == 'node_event_form') {
    $form['field_location']['widget'][0]['#after_build'][] = 'nys_contrib_alters_customize_address';
  }
}

function nys_contrib_alters_customize_address($element, $form_state) {
  $element['address']['organization']['#title'] = t('Location Name');
  $element['address']['address_line2']['#title_display'] = 'before';
  return $element;
}