<?php

namespace Drupal\nys_feeds;

use Drupal\Component\Plugin\PluginBase;
use Drupal\Core\Cache\CacheableJsonResponse;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Entity\Query\QueryInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * Base class for NYS Feeds plugins.
 */
abstract class NysFeedPluginBase extends PluginBase implements NysFeedPluginInterface {

  /**
   * Holds any cache metadata generated by the feed.
   *
   * @var \Drupal\Core\Cache\CacheableMetadata
   */
  protected CacheableMetadata $cache;

  /**
   * A FeedInput object.
   *
   * @var \Drupal\nys_feeds\FeedInput
   */
  protected FeedInput $input;

  /**
   * The query string parameters merged/filtered with the plugin defaults.
   *
   * @var array
   */
  protected array $resolvedParams = [];

  /**
   * The HTTP status code desired in the return.
   *
   * @var int
   */
  protected int $statusCode = 200;

  /**
   * Holds the output state of the feed.
   *
   * @var \Drupal\nys_feeds\FeedOutput
   */
  protected FeedOutput $output;

  /**
   * {@inheritDoc}
   *
   * Adds Drupal's Entity Type Manager service.
   */
  public function __construct(protected EntityTypeManagerInterface $entityTypeManager, array $configuration, $plugin_id, $plugin_definition) {
    parent::__construct($configuration, $plugin_id, $plugin_definition);

    // Verify the FeedInput is as expected.
    $this->input = $configuration['input'] ?? NULL;
    if (!(($this->input) instanceof FeedInput)) {
      throw new \InvalidArgumentException("NysFeed plugin called without a valid FeedInput");
    }

    // Initialize the cache, output object, and parameters.
    $this->cache = new CacheableMetadata();
    $this->output = new FeedOutput();
    $this->initParams();
  }

  /**
   * {@inheritDoc}
   *
   *  Adds Drupal's Entity Type Manager service.
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition): static {
    return new static(
      $container->get('entity_type.manager'),
      $configuration,
      $plugin_id,
      $plugin_definition);
  }

  /**
   * Gets an attribute parameter from the plugin definition.
   */
  public function getParameter(string $name): mixed {
    return $this->getParameters()[$name] ?? NULL;
  }

  /**
   * Wrapper method to retrieve all plugin parameters.
   */
  public function getParameters(): array {
    return $this->getPluginDefinition()['params'] ?? [];
  }

  /**
   * Initializes defined parameters with their defaults, and the query string.
   */
  protected function initParams(array $query = []): void {
    $this->resolvedParams = [];
    $query = $query ?: $this->input->getQueryString();
    foreach ($this->getParameters() as $name => $value) {
      $this->resolvedParams[$name] = $query[$name] ?? $value;
    }
    $this->resolveParams();
  }

  /**
   * Get the filtered array of resolved parameters to use as cache context.
   */
  protected function getCacheParams(): array {
    return array_filter($this->resolvedParams);
  }

  /**
   * Allows children to transform configured parameters.
   */
  protected function resolveParams(): void {
  }

  /**
   * Instantiates an entity query based on the plugin definition.
   *
   * Leverages the definition's entity_type and bundle properties.
   *
   * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
   * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
   */
  protected function getQuery(): QueryInterface {
    $type = $this->getPluginDefinition()['entity_type'];
    $bundle = $this->getPluginDefinition()['bundle'];
    $bundle_field = $this->entityTypeManager->getDefinition($type)
      ->getKey('bundle');
    $query = $this->entityTypeManager->getStorage($type)->getQuery()
      ->condition($bundle_field, $bundle, '=')
      ->condition('status', 1)
      ->accessCheck();
    $this->alterQuery($query);
    return $query;
  }

  /**
   * Allows children to customize the base entity query.
   */
  protected function alterQuery(QueryInterface $query): void {
  }

  /**
   * Creates/fetches the relevant data.
   */
  protected function query(): array {
    try {
      $type = $this->getPluginDefinition()['entity_type'];
      $found = $this->getQuery()->execute();
      $result = $this->entityTypeManager->getStorage($type)
        ->loadMultiple($found);
    }
    catch (\Throwable $e) {
      $result = [];
      $this->output->messages['exception'] = $e->getMessage();
      $this->output->statusCode = 500;
    }
    $ret = [];
    foreach ($result as $row) {
      $ret[$row->id()] = $row;
    }
    return $ret;
  }

  /**
   * Transcribes a single entry into a JSON-ready array.
   */
  protected function transcribeEntry(mixed $data): mixed {
    return $data;
  }

  /**
   * Constructs the cache ID.
   */
  protected function cacheId(): string {
    return 'nys_feeds:' . $this->getPluginId();
  }

  /**
   * Builds the cache contexts for the individual plugin.
   */
  protected function buildContext(): void {
    if ($this->useCache()) {
      // Add the bundle-specific entity list tag.
      $def = $this->getPluginDefinition();
      $list_tag = $def['entity_type'] . '_list:' . $def[`bundle`];
      $this->cache->addCacheTags([$list_tag]);

      // Add the query string contexts.
      $context = array_map(
        fn($v) => "url.query_args:$v",
        array_keys($this->getCacheParams())
      );
      $this->cache->addCacheContexts($context);
    }
  }

  /**
   * {@inheritDoc}
   */
  public function getFeed(): FeedOutput {
    $data = $this->query();
    $output = new FeedOutput();
    foreach ($data as $key => $val) {
      // Add the entry as data...
      $output->data[$key] = $this->transcribeEntry($val);
      // ...and a cache dependency.
      $this->addDependency($val);
    }

    // This comment intentionally left blank.
    if (!count($data)) {
      $output->messages[] = "No data found";
    }

    // Add the cache context.
    $this->buildContext();

    return $output;
  }

  /**
   * {@inheritDoc}
   */
  public function getResponse(FeedOutput $output): JsonResponse {
    if ($this->useCache()) {
      $cache_age = ($this->getPluginDefinition()['max_cache_age']) ?? 0;
      $ret = (new CacheableJsonResponse($output->asArray()))
        ->addCacheableDependency($this->cache)
        ->setMaxAge($cache_age);
    }
    else {
      $ret = new JsonResponse($output->asArray());
    }
    $ret->setStatusCode($output->statusCode);
    return $ret;
  }

  /**
   * Adds a dependency only if the plugin is configured as cacheable.
   */
  protected function addDependency(mixed $value): void {
    if ($this->useCache()) {
      $this->cache->addCacheableDependency($value);
    }
  }

  /**
   * Wrapper around the 'cacheable' configuration attribute.
   */
  public function useCache(): bool {
    return (bool) (($this->getPluginDefinition()['cacheable']) ?? TRUE);
  }

}
