name: 'Chart.js Charts'
type: module
description: 'Charts module integration with Chart.js.'
package: Charts
core_version_requirement: ^9.2 || ^10
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2024-01-10
version: '5.0.10'
project: 'charts'
datestamp: 1704898553
