# Schema for configuration files of the Password Policy Length submodule.

password_policy.constraint.plugin.password_length:
  type: password_policy.constraint.plugin
  mapping:
    character_length:
      type: integer
    character_operation:
      type: string
