geolocation.map_provider.google_static_maps:
  type: geolocation_map_provider
  label: 'Google Map settings'
  mapping:
    type:
      type: string
      label: 'Google map type'
    zoom:
      type: integer
      label: 'Zoom level'
    height:
      type: integer
      label: 'Height value'
    width:
      type: integer
      label: 'Width value'
    format:
      type: string
      label: 'Format value'
    scale:
      type: integer
      label: 'Scale integer'
