name: Charts
type: module
description: 'A charting API for Drupal that provides chart elements and integration with Views.'
package: Charts
core_version_requirement: ^9.2 || ^10
configure: charts.settings

# Information added by Drupal.org packaging script on 2024-04-26
version: '5.0.13'
project: 'charts'
datestamp: 1714145380
