name: Pantheon Refresh Training Multidev

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Please confirm that you would like to refresh the training environment with the latest code and a database from https://www.nysenate.gov/. This action cannot be undone.'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}

      - name: Disable Pantheon SSH strict host key checking
        run: 'printf "\nHost *\n\tStrictHostKeyChecking no" >> ~/.ssh/config'

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Merge the latest code from master into training.
        run: terminus multidev:merge-from-dev ${{ vars.PANTHEON_SITE }}.training --yes

      - name: Refresh Training Environment with a database from Live (no files)
        run: terminus env:clone-content ${{ vars.PANTHEON_SITE }}.live training --yes --db-only
