field.formatter.third_party.address_map_link:
  type: mapping
  label: 'Address map link configuration'
  mapping:
    link_address:
      type: boolean
      label: 'Link Address to Map'
    map_link_type:
      type: string
      label: 'Map Link Type'
    map_link_position:
      type: string
      label: 'Map Link Position'
    map_link_text:
      type: string
      label: 'Map Link text'
    map_link_new_window:
      type: boolean
      label: 'Open map in new window'
