#
# DrupalCI includes.
#
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

#
# Start custom overrides.
#
variables:
  #  Disable default phpunit job in favor of the d9/10 variants below.
  SKIP_PHPUNIT: 1
  _PHPUNIT_EXTRA: --verbose

# Run two variations of composer job.
composer:
  parallel:
    matrix:
      - _TARGET_PHP: [ "7.4" ]
        _TARGET_CORE: [ "9.5.x" ]
      - _TARGET_PHP: [ "8.1" ]
        _TARGET_CORE: [ "$CORE_STABLE" ]
      - _TARGET_PHP: [ "8.3" ]
        _TARGET_CORE: [ "$CORE_STABLE" ]

phpcs:
  needs:
    - "composer: [8.3, $CORE_STABLE]"

composer-lint:
  needs:
    - "composer: [8.3, $CORE_STABLE]"

eslint:
  needs:
    - "composer: [8.3, $CORE_STABLE]"

stylelint:
  needs:
    - "composer: [8.3, $CORE_STABLE]"

.phpunit-local:
  variables:
    SKIP_PHPUNIT: 0

phpunit-d9:
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: "7.4"
            _TARGET_CORE: "9.5.x"
  variables:
    _TARGET_PHP: "7.4"
  extends:
    - .phpunit-base
    - .phpunit-local

phpunit-d10-81:
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: "8.1"
            _TARGET_CORE: $CORE_STABLE
  variables:
    _TARGET_PHP: "8.1"
  extends:
    - .phpunit-base
    - .phpunit-local

phpunit-d10-83:
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: "8.3"
            _TARGET_CORE: $CORE_STABLE
  variables:
    _TARGET_PHP: "8.3"
  extends:
    - .phpunit-base
    - .phpunit-local
